### ISSUE TITLE
Generate the cluecumber report despite failure of tests

### ISSUE THREAD

**Issue by bbarman4u** [trivago/cluecumber-report-plugin#100]
I am not sure if this is the intended feature currently but it requires two steps in order to view the cluecumber report by explicitly calling the cluecumber goals if there is a test failure( either from surefire or failsafe plugin). It would be nice if despite the build failure status it would still execute the reporting phase somehow. 

I am sorry if there is already another recommended approach for it that I could not find.
P.S. - I know its possible to do in a CI platform with multi step process but on local environment every time it needs 2 steps.
Thanks in advance.

**Comment by laxersaz** [comment]
Hi, this is standard Maven behavior. Please look at https://github.com/trivago/cluecumber-report-plugin/issues/49
