### ISSUE TITLE
How to add a screenshot after a step fails

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cluecumber-report-plugin#110]
I am using Cucable along with Cluecumber report plugin, I am facing a difficulty in understanding the fact that how to add a screenshot in report after a step fails.
I can take screenshots using Selenium built in library but the problem is how to add it in report. Is there any built in function Cluecumber report library that I need to call?
Please suggest.

**Comment by laxersaz** [comment]
Your test framework has to take care about taking and attaching screenshots. 
Cluecumber just takes the generated JSON files and generates reports from them. So everything that is included in the JSON is showing up in the report in the end.

So after taking the screenshot, you need to attach it to the scenario within your test framework, e.g. in an after hook:

```
scenario.embed(screenshot, "image/png");
```

Whatever is attached to a scenario will be encoded in the resulting JSON files that Cluecumber then processes.

**Comment by jaydeepqa** [comment]
Got it, thanks for your answer.
