### ISSUE TITLE
Tag Summary view is blank in html report despite features being tagged

### ISSUE THREAD

**Issue by Galileo1** [trivago/cluecumber-report-plugin#111]
**Describe the bug**
Tag Summary Page of the HTML report is blank.

**To Reproduce**
1. Run test (that have feature level tags and not scenario level tags) in default parallelizationMode.
2. Check the cluecumber json report.
3. At the very bottom you might see that tags block.
4. Check the cluecumber html report and click on Tag Summary view.
5. The report doesn't show any data.

**Expected behavior**
The tag summary report would have shown the test case result grouped by tag.

**Attachments**
1. JSON report has feature level tags - 
![cluecucumber json report has tags](https://user-images.githubusercontent.com/9716232/50666894-9a46bf80-101b-11e9-8857-80a749b3850f.PNG)

2. HTML report doesn't show tag summary.
![cluecucumber html report has no tag summary](https://user-images.githubusercontent.com/9716232/50666909-b21e4380-101b-11e9-8a15-6a7e1e0bfbac.PNG)

**Additional context**
The tests were running in parallel on scenario basis. Does that mean that if tags are at feature level they wont be displayed in tags summary? Scenario inherits feature level tags.

**Comment by laxersaz** [comment]
Hello @Galileo1 , is it possible to send me your generated JSON so I can use the exact data you have to reproduce this behavior?

**Comment by Galileo1** [comment]
Hi @laxersaz , I have attached the json file. All other pages are displaying the correct data. I checked the browser console for if there are any errors or something is breaking on tag summary report but nothing's there. 
[test json file.txt](https://github.com/trivago/cluecumber-report-plugin/files/2730790/test.json.file.txt)

**Comment by laxersaz** [comment]
I'm looking into this one

**Comment by laxersaz** [comment]
This is a valid bug that I will fix for release 1.6.3

**Comment by laxersaz** [comment]
Ready for release in 1.6.3
