### ISSUE TITLE
How to add custom message and remove Before and After in cluecumber report

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cluecumber-report-plugin#112]
I want to add a custom message to a particular step, hence I did the following but failed : 
First, I added my custom message like : 
scenario.write("The field is not displayed").
Now post generation of html report , I see the text is not coming instead a white space is appearing.
You can check my attached screenshot below. How to mitigate this..any idea
![image](https://user-images.githubusercontent.com/28946503/50733111-13295100-11ad-11e9-86db-64d5352cdee8.png)

Second question is, if you see my above screenshot you will see all Before and After tags appearing in report, now if I want to hide them is it possible?

**Comment by laxersaz** [comment]
Hi @jaydeepqa ,
could you please add the generated JSON so I can test it with your original data?
Thanks,
Benjamin

**Comment by jaydeepqa** [comment]
Please find attached the Json file.
Also note that I was opening the html file in IE edge, so the screenshot shared with you earlier was of IE edge. However when opened in Chrome, the text is coming but the text is coming in a white box which doesn't look good.
[HomePage_scenario001_run001_IT.zip](https://github.com/trivago/cluecumber-report-plugin/files/2733044/HomePage_scenario001_run001_IT.zip)

In Chrome
![image](https://user-images.githubusercontent.com/28946503/50773045-af3e7f80-12b5-11e9-9033-6a03cc3e3ba6.png)

**Comment by laxersaz** [comment]
The Cluecumber version you are using is very old. The current one is 1.6.2
1.6.3 is coming out tomorrow which will also introduce showing and hiding scenario hooks.
