### ISSUE TITLE
Does cluecumber report plugin support any other status apart from Pass/Fail for example status like Warning

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cluecumber-report-plugin#113]
Does cluecumber report plugin support any other status apart from Pass/Fail for example status like Warning.
I personally think this would be very useful for scenarios like for example, in one test case if I have to test whether 20 fields are appearing or not, in that case I have 20 gherkin lines for 20 fields then if one field in between doesn't appear then the test fails there is no way I could execute the entire test case to check all the fields, hence some fields remain untested until the bug is fixed we can't/don't run it again. However if those steps are marked as Warning instead of fail and it continues with the execution, it would help.

**Comment by laxersaz** [comment]
As Cluecumber does not execute any tests but only takes the generated JSON and turns it into reports, this is something you need to tackle in your test framework.
