### ISSUE TITLE
Broken cluecumber reports

### ISSUE THREAD

**Issue by ktohan** [trivago/cluecumber-report-plugin#119]
On karate test execution we are getting these broken reports. Can you please have a look ?

![demo](https://user-images.githubusercontent.com/46044874/51193620-8b002580-18e9-11e9-8055-e142c0430143.PNG)
![demo2](https://user-images.githubusercontent.com/46044874/51193628-8fc4d980-18e9-11e9-8721-443eba633592.PNG)

**Comment by laxersaz** [comment]
Thanks for reporting this. It seems like long scenario names without spaces break the layout.

**Comment by laxersaz** [comment]
Ready for release in 1.6.4
