### ISSUE TITLE
No resizement of embeded html (iframes) when expanding the after step/scenario hooks sections

### ISSUE THREAD

**Issue by valdeziscoming** [trivago/cluecumber-report-plugin#121]
html height of iframe not set after expanding steps/scenario hooks

1. Embed a html with fixed size within a afterStep/afterHook scenario e.g.

`<div align='center' style='height: 150px'><a href='https://www.google.com' target='_blank'>Google..</a></div>`

2. Click on Show Step Hooks / Senario Hook button
3. Scroll down to the expanded sections
4. the height of the embeded iFrame is 25px (default value), the content is not full visible

**Expected behavior**
The height should be calculated new, after expanding the hook sections (by calling resizeIFrame ?)

**Comment by laxersaz** [comment]
Fixed in version 1.6.5
