### ISSUE TITLE
Tag summary giving wrong tagged scenario count

### ISSUE THREAD

**Issue by abhishek8908** [trivago/cluecumber-report-plugin#124]
**Describe the bug**
Tag summary giving wrong tagged scenario count.

**To Reproduce**
1. Create a cucumber scenario and give it multiple tags, let's say 3.
2. Run the scenario.
3. Verify the Tag summary page

**Actual Behavior***
Tagged Scenario count is 3 , sum of all tags count.

**Expected behavior**
Tagged Scenario count should be 1 as there is only one scenario that ran which has 3 tags.

**Comment by laxersaz** [comment]
Ready for release in 1.7.0
