### ISSUE TITLE
Is there any way to handle historical data of all automation runs in a single dashboard.

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cluecumber-report-plugin#126]
When we run a html report gets generated. Now after say 20-40 runs or maybe more it will be difficult to analyze all the runs if required, for that al individual html report needs to be opened. Is there any way a consolidated dashboard can be created, where user can click on day's run and check that particular html report.

**Comment by laxersaz** [comment]
Hi! Cluecumber's purpose is to generate a test report of a single run. So if you want to have the functionality that you describe, the reporting would need to keep state of all previous runs. This is out of scope and needs to be solved outside of Cluecumber.
We use kibana to log, report and analyze our test history and from there we can easily go to the Cluecumber report of the relevant historical runs.

**Comment by jaydeepqa** [comment]
Can you please tell some more a bit that how you use Kibana to log, report
and analyze test history, as I want to do the same, any tutorial/guidelines
will be really helpful.

Thanks!

**Comment by laxersaz** [comment]
Sorry, I can't since this is internal information.
But there is for sure a lot of information out there.
