### ISSUE TITLE
Add test start time to report

### ISSUE THREAD

**Issue by josepj** [trivago/cluecumber-report-plugin#127]
I see that the report currently shows the test execution date and end time on the header. Would it be possible to add the execution start time too to the report? This would help provide an approximate actual run time in case of parallel test execution (related to #114).

**Comment by laxersaz** [comment]
Hi @josepj 
This is a great idea. I will see what I can do :-)
Best,
Benjamin

**Comment by laxersaz** [comment]
As this information is not contained within the Cucumber JSON and the file creation date is a very unreliable indicator for the test execution (especially after copying the report files on Jenkins), this is a won't fix. Also, the time in the report is the report creation date and time and not the test creation date and time.
