### ISSUE TITLE
how to run report using maven surefire plugin and cucmber jvm parellal plugni

### ISSUE THREAD

**Issue by kadamAbhijeetBalasaheb** [trivago/cluecumber-report-plugin#128]
i am using 

<groupId>com.github.temyers</groupId>
				<artifactId>cucumber-jvm-parallel-plugin</artifactId>
				<version>4.2.0</version>

and 

<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20</version>

how to integrate report with above settings

**Comment by laxersaz** [comment]
Cucable just takes JSON files and generates reports from them. So it does not need to be integrated with those plugins. Instead, it has to be defined in the Maven lifecycle so it can be either invoked automatically after the tests are run (e.g. `mvn clean verify`) or called separately after the tests are run using `mvn cluecumber-report:reporting`.
