### ISSUE TITLE
Adding abililty to hide total duration from report

### ISSUE THREAD

**Issue by gazler22** [trivago/cluecumber-report-plugin#129]
It looks like the total duration that the report shows when the test cases are running in parallel (using cucable for example), is not the total time taken to run the since cluecumber does not know which scenarios ran in parallel and is actually showing the sum of the total time taken by each scenario.

Refer : 
https://github.com/trivago/cluecumber-report-plugin/issues/114 

It would be great then if there is an option to configure the plugin to **not** show the total time in the report so that it is not misleading if we are sending a mail with the report attached or something.

An option to hide the time taken would be much appreciated. Thank You.

**Comment by laxersaz** [comment]
I will think about your suggestion. Until then it might also be possible to hide the time by using a custon css.

**Comment by gazler22** [comment]
Yes it will be great if we can do that. I will look into how I can hide the time using css meanwhile, I am not very versed with it.

Thank You!

**Comment by laxersaz** [comment]
I introduced some data attributes in the html code. So in version 1.7.0, you will be able to add a custom css file that needs to contain:

```
[data-cluecumber-item="total-scenario-duration"] {
    display: none;
}
```

in order to hide the total time.

**Comment by laxersaz** [comment]
Ready to release for 1.7.0
