### ISSUE TITLE
Running "mvn com.trivago.rta:cluecumber-report-plugin:1.6.5:reporting" results in error 'parameters for goal reporting are missing or invalid'

### ISSUE THREAD

**Issue by akshattambe** [trivago/cluecumber-report-plugin#130]
**Describe the bug**
Running "mvn com.trivago.rta:cluecumber-report-plugin:1.6.5:reporting" results in below errro -
'cluecumber-report-plugin: The parameters 'generatedHtmlReportDirectory', 'sourceJsonReportDirectory' for goal com.trivago.rta:c
luecumber-report-plugin:1.6.5:reporting are missing or invalid'

**To Reproduce**
1. Get the fresh clone in your local
2. Open the project in IntelliJ
3. Add POM files for plugin-code and example-project
4. Import all dependencies
5. set below params
      <sourceJsonReportDirectory>${project.build.directory}/cucumber-report
      </sourceJsonReportDirectory>
      <generatedHtmlReportDirectory>${project.build.directory}/generated-report
      </generatedHtmlReportDirectory>
5. Run "mvn com.trivago.rta:cluecumber-report-plugin:1.6.5:reporting"

**Expected behavior**
The program should run successfully and reports should get generated at the expected location

**Attachments**
1. Here is the screenhsot of the terminal - 
![image](https://user-images.githubusercontent.com/20226086/52533859-a02a7180-2d3a-11e9-8779-a12cc8e15bb3.png)

2. POM file chages - 
![image](https://user-images.githubusercontent.com/20226086/52533912-d8ca4b00-2d3a-11e9-8257-fab2a6c873da.png)

**Additional context**
I was expecting to generate the reports OOB after the execution. Please share if I am missing any configuration. I am new to maven and trying to understand how does this plugin works. I want to introduce it as a reporting tool in my current project.

I tried to use [this ](https://github.com/trivago/cluecumber-report-plugin/issues/40) solution as well from the documentation issue but getting the same error.

Thanks for your help in advance
Akshat

**Comment by laxersaz** [comment]
If you want to execute the reporting directly, the `configuration` block needs to be moved  so it appears after the `executions` block. Otherwise this configuration is just for the `post-integration-test` phase.

**Comment by akshattambe** [comment]
Hi, I did move the configuration block. I am getting this error now - 
 Unable to traverse JSON files in C:\dev\cluecumber-report-plugin\example-project\target/cucumber-repor

I read about this issue as well - https://github.com/trivago/cucable-plugin/issues/83
but not sure what changes in have to do at my end.

**Comment by akshattambe** [comment]
> Hi, I did move the configuration block. I am getting this error now -
> Unable to traverse JSON files in C:\dev\cluecumber-report-plugin\example-project\target/cucumber-report
> 
> I read about this issue as well - [trivago/cucable-plugin#83](https://github.com/trivago/cucable-plugin/issues/83)
> but not sure what changes I have to do at my end.
> 
> Current POM file after new changes -
> ![image](https://user-images.githubusercontent.com/20226086/52534274-e0402300-2d3f-11e9-9c6f-a05455f5f710.png)

Hi, just wanted to check if you have got any thoughts on this.

**Comment by laxersaz** [comment]
You are running the reporting step against a directory which doesn't exist. Your configuration is pointed to `${project.build.directory}/cucumber-report` which does not contain any json files when you invoke `cluecumber-report-plugi:reporting` without running tests first. 

So you should change the location to `${project.basedir}/json` (as it is done in the example project).

**Comment by laxersaz** [comment]
Please let me know if this answers it.

**Comment by akshattambe** [comment]
Yes, it is now working...thank you :)

**Comment by nived001** [comment]
When I run cucumber tests then it will generate json file and after that, I should trigger the command manually to generate the report.

How could I automate this process?

**Comment by laxersaz** [comment]
Your question does not really fit into this issue.

It highly depends on your setup and how you run the test. In general, it shouldn't be necessary to run the reports manually.

**Comment by nived001** [comment]
I agree, mvn -e clean install is my goal, then it will run all the tests and generates json, Then again I should trigger the command to generate this report,

Could you tell me how to configure for automate the process?

**Comment by laxersaz** [comment]
Sorry, like I said, this is out of scope here.
