### ISSUE TITLE
Reporting failure in Json instead of calling Assert

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cluecumber-report-plugin#131]
My goal is to continue on failure for some steps.
For that to happen, are you aware of any way to mark a step as fail in Json report instead of calling Assert which fails and halts the execution there itself.
Actually the situation is like, I have to insert data in 30 fields for example and then click save, post that I need to check whether data is present in each and every 30 fields, if there is any failure in any step while verifying data in all the 30 fields, I want to continue with the execution and come out with all the failures at once so that a consolidate defect can be logged.
I can do one way like instead of calling assert, I can capture the status in a boolean variable and check the boolean value in @After and then call Assert if there is a failure, but doing that though will fail the test case at the end but all the steps will appear as Pass and it will be very difficult to dig out the actual fail reason at later point of time while verifying the results.
Hope you can shed some light on this.

**Comment by laxersaz** [comment]
Hello,
this question is unrelated to Cluecumber which takes the final json results AFTER the test runs and generates reports from them. Your question is about how your tests and test framework should be set up to achieve this.
My personal view: fail fast. If you need granular failure reasons split up your test cases.
Sorry I cannot help further.

**Comment by jaydeepqa** [comment]
Thanks for your reply,but I couldn't understand that what you tried to mean
when you said "fail fast"

**Comment by laxersaz** [comment]
I prefer fast feedback of tests. So when there is a failure it should be a fast failure. If subsequent steps are run after a failed step and the failure is recorded on scenario end this can be quite a long delay.
