### ISSUE TITLE
Hook execution times are not reflected in the test duration total

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#135]
I am running cucumber 4.2.3 using failsafe plugin 3.0.0-M3 with 2 runners in parallel using junit 4.12. 
```
            <parallel>classesAndMethods</parallel>
	    <threadCount>4</threadCount>
```
There is nothing much in the scenario steps except for print statements. I have a before hook which takes a scenario object. Also there is a beforestep hook which has a thread sleep of 2secs.

In the Scenario Summary page the total duration does not include the beforestep execution times.
![summary](https://user-images.githubusercontent.com/10829355/53635842-5d2a3280-3c44-11e9-8b0d-e08abbfb7ca7.png)

This is also not included in the individual Summary page.
![individual summary](https://user-images.githubusercontent.com/10829355/53636064-f3f6ef00-3c44-11e9-89cb-fb9071b0ab88.png)

Though the hook duration times are displayed for each hook and steps in the detailed table.
![individual summary stephook details](https://user-images.githubusercontent.com/10829355/53636177-4b955a80-3c45-11e9-82d2-5a725d86572c.png)

I am using this configuration setting for the plugin
```
<configuration>
     <sourceJsonReportDirectory>
               ${project.build.directory}/json-cucumber-reports
    </sourceJsonReportDirectory>
    <generatedHtmlReportDirectory>
              ${project.build.directory}/generated-report
    </generatedHtmlReportDirectory>
    <expandBeforeAfterHooks>true</expandBeforeAfterHooks>
    <expandStepHooks>true</expandStepHooks>
</configuration>
```

I am getting the same result when i switch to a single runner too or change parallel setting to 'methods'. 

Is there some setting or I am missing something? Thanks

**Comment by laxersaz** [comment]
Hello @grasshopper7 ,
thanks a lot for reporting this. This is indeed a bug - I will fix this one for the next release.

**Comment by grasshopper7** [comment]
@laxersaz U r welcome. If this has any relevance, I am running this on Windows 8.

**Comment by laxersaz** [comment]
Fixed in 1.7.2

**Comment by laxersaz** [comment]
@grasshopper7 this was just released. It should be available on Maven central soon.

**Comment by grasshopper7** [comment]
The total duration summary is adding up the times for hook execution. But the steps duration are also adding up the hook times.

Refer to screen of Scenario Details in 1.7.1
![ver1 7 1](https://user-images.githubusercontent.com/10829355/53832771-0bb7d580-3fad-11e9-8e79-aa0bae45b2ae.png)

Refer to screen of Scenario Details in 1.7.2
![ver1 7 2](https://user-images.githubusercontent.com/10829355/53832796-14a8a700-3fad-11e9-95a3-1ff4141b6fcf.png)

**Comment by laxersaz** [comment]
Ah I see. What you say is true because in Cucumber, the step hooks have their own time. I just wanted to make it visible that the step (including its hooks) took a specific time.
But yeah, technically the step itself took 0ms and only its hooks took time.
Thanks for mentioning this - I will change that for the next iteration.

**Comment by laxersaz** [comment]
Hello @grasshopper7 ,
the fix will be released on Monday.

**Comment by laxersaz** [comment]
Release done, should be on Central soon :-)
