### ISSUE TITLE
Duration value in "Scenario Summary" page is not valid for parallel execution

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#138]
Using the report plugin with parallel execution. Have 2 runners and the following is the failsafe setting in POM.
```
      <parallel>classesAndMethods</parallel>
      <threadCount>2</threadCount>
      <perCoreThreadCount>true</perCoreThreadCount>
```
Below is the project structure. FirstRunner executes the feature files in first colder and generates the json report. Similar for the other runner.

![proj](https://user-images.githubusercontent.com/10829355/53837951-e7aec100-3fb9-11e9-92aa-a6573b113935.png)

In the maven console both of these runners takes 18 secs to execute parallely. And the total build time is 31 secs.
![paralleltimes](https://user-images.githubusercontent.com/10829355/53838054-2ba1c600-3fba-11e9-8d8e-6080b01929cc.png)
![build](https://user-images.githubusercontent.com/10829355/53838059-30667a00-3fba-11e9-893b-f158aa4b31a3.png)

But in the report generated it is shown around 1 min. Basically all the step and hook times have been added as if they were executed serially.
![summary](https://user-images.githubusercontent.com/10829355/53838151-6146af00-3fba-11e9-832b-e88e22f6acff.png)

**Comment by laxersaz** [comment]
Cluecumber has no awareness of tests being executed in parallel or sequence. Also the generated json files by Cucumber do not reflect this but the complete scenario runtime. That's why the displayed time is technically correct.

**Comment by grasshopper7** [comment]
It is technically correct but it is pretty difficult to explain the difference with the actual execution times to a report user. Maybe the json files need to be modified as in including actual start and finish times. How about a custom plugin which pulls this data for Cluecumber report?

**Comment by laxersaz** [comment]
Sure this could be solved by a custom plugin and/or modifying the json data. However, this would be outside of Cluecumber's scope. The main goal of Cluecumber is compatibility to the Cucumber json format.
However, this is something that I will discuss with the Cucumber OSS group as well. Maybe it is possible to support this in their native JSON files.

**Comment by laxersaz** [comment]
In the meantime you can also hide the total duration as described here:
https://github.com/trivago/cluecumber-report-plugin/blob/master/README.md#customcss

**Comment by laxersaz** [comment]
I started a thread in the Cucumber OSS group.

**Comment by laxersaz** [comment]
There is a PR in progress for Cucumber to add the start times to the JSON files. I am monitoring this one to see when it will be available.

**Comment by grasshopper7** [comment]
Great. Thanks for all the effort.

**Comment by laxersaz** [comment]
Ready for release.
