### ISSUE TITLE
Page not Found issue 

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cluecumber-report-plugin#140]
**Describe the bug**
i am running over 6000 scenario as part of regression suite. 
html pages were missing for some passed and failed  scenarios 

**To Reproduce**
1. Go to clucumber report
2. Click on 'any passed or failed' scenario
3. page Not found error:
![image](https://user-images.githubusercontent.com/22300715/54048973-379faa80-41a9-11e9-83b1-3e41d2418f9d.png)
.

**Expected behavior**

**Attachments**
If applicable, add screenshots or sample JSON files to help explain your problem.

**Additional context**

**Comment by laxersaz** [comment]
This was fixed in https://github.com/trivago/cluecumber-report-plugin/issues/108
