### ISSUE TITLE
Allowing locally shared files to be recognized as links

### ISSUE THREAD

**Issue by gazler22** [trivago/cluecumber-report-plugin#142]
We have some files and logs generated from our cucumber suite shared on a location on the company network to which I give a link to in the failure of each test case for easy access to logs regarding that particular scenario.

Right now, the RenderingUtils pattern only recognizes ftp/http/https patterns which is correct. But if possible I would also like to add "file" to this so that locally shared locations are also clickable in the report as links to access these files, eg:

"file:\\machine_name\somefolder\somefile"

I already made the changes. I can create a pull request if thats fine.

**Comment by laxersaz** [comment]
Hello! Yes that would be great!

**Comment by laxersaz** [comment]
Hello @gazler22 ,
sorry for the delay - this will be released on Monday.

**Comment by gazler22** [comment]
Wonderful. Thank You!

**Comment by laxersaz** [comment]
Release done, should be on Central soon :-)
