### ISSUE TITLE
Showing step failure frequency

### ISSUE THREAD

**Issue by gazler22** [trivago/cluecumber-report-plugin#145]
I am thinking maybe we can have another statistic in the report where we can show the frequency of failed test steps.

This could be useful in quite a few cases, eg: if multiple test cases have the same Background/Step in them (for eg: connecting to server) and if most of them fail at that step during execution (because maybe the server was down), then the report showing something like :

**Steps Failure Frequency: ** 
_Given I connect to server (70 times)
Given I did something (5 times)
Given I did something else (5 times)_

would be pretty useful for anyone to see and know at a first glance that the server is probably down (without having to go through the first 10-20 scenarios in the report to figure out if the problem is the same).

I can start working on this if that's fine.

**Comment by laxersaz** [comment]
I already started working on a step overview that is supposed to collect data about each step. :-)

**Comment by gazler22** [comment]
Oh thats good to know. I think this feature would be really useful :)

**Comment by laxersaz** [comment]
Released in version 1.8.0
