### ISSUE TITLE
How to add multiple custom parameters in clue cumber report ?

### ISSUE THREAD

**Issue by rahulbommanaboina** [trivago/cluecumber-report-plugin#151]
Hi Team,

As of now when i try to add multiple custom parameters, only the last parameter is appearing on the report start page.

Is there a way we can add multiple parameters ?

                         <Custom_Parameter>Test1</Custom_Parameter>
                        <Custom_Parameter>Test2</Custom_Parameter>

Only Test 2 is appearing

**Comment by laxersaz** [comment]
Hi!
You are using this wrong because you use two parameters with the same name - in this case the first parameter is overwritten.

Please check the documentation on how to use it correctly:
https://github.com/trivago/cluecumber-report-plugin#customparameters

**Comment by rahulbommanaboina** [comment]
Great !! Understood , Thank you !!
