### ISSUE TITLE
Unable to open video link / html link in clue cumber report - trivago

### ISSUE THREAD

**Issue by rahulbommanaboina** [trivago/cluecumber-report-plugin#159]
I tried to embed sauce lab video link to the clue cumber report and i was successfully able to add the link but when i click on it nothing is happening. two issues: 1. nothing happening when clicked on link in IE browser and if i inspect the element and open the link in another tab , i was able to see the video playing in windows media player 2.not able to find pie charts and links in Chrome browser , when i inspect the page , there i see many errors in the console .
OS windows 10
IE - Version 11
Chrome - 73.0.3683.103
String videoLink = "<a href="ReusableMethodToGetVideoLink">Video<a>";
        scenario.embed(videoLink.getBytes(StandardCharsets.UTF_8), "text/html");

**Comment by laxersaz** [comment]
Hello, can you give me some more information about which version you are using? Also, an example JSON would help a lot.

**Comment by rahulbommanaboina** [comment]
Hi Laxersaz,

	<dependency>
		    <groupId>com.trivago.rta</groupId>
		    <artifactId>cluecumber-report-plugin</artifactId>
		    <version>1.7.0</version>
		</dependency>

Cannot provide complete json , hope you understand :) here is the part for the video link am trying to attach in the cucumber.json report.

"embeddings": [
              {
                "data": "aHR0cHM6Ly9hc3NldHMuc2F1Y2VsYWJzLmNvbS9qb2JzLzkxYmYzZWU3Y2QwMTRiOTk5MTc4M2VlZWRhNzM4MjZhL3ZpZGVvLm1wNA\u003d\u003d",
                "mime_type": "text/html"
              },

**Comment by rahulbommanaboina** [comment]
<img width="868" alt="test" src="https://user-images.githubusercontent.com/29060552/56888903-c4bcfc80-6a92-11e9-8b20-8379e6b35821.PNG">

**Comment by laxersaz** [comment]
I added content security policies to Cluecumber 1.10.1 which will be released today. I will let you know when it is available.

**Comment by rahulbommanaboina** [comment]
Yeah great !! Thank you !!

**Comment by laxersaz** [comment]
For your other issue, if you want to see a link, you need to attach the html code to create a link (`<a href='some_url' target='_blank'>your link text</a>`) and not only the link text itself.

Then it works (tested with current version 1.10.0)
![image](https://user-images.githubusercontent.com/5775857/56896169-545ead00-6a8b-11e9-93cf-b0ea0e830295.png)

**Comment by laxersaz** [comment]
Release of v1.10.2 is done.

**Comment by rahulbommanaboina** [comment]
Yeah thank you somuch , ill test this today and let you know , regarding
html code , can you please send any sample code it might help me :)

Regards,
Rahul B

**Comment by rahulbommanaboina** [comment]
Ok understood , giving _blank in target leads to open new tab , thank you ,
ill try with this.

Regards,
Rahul B

**Comment by rahulbommanaboina** [comment]
<img width="842" alt="Bug" src="https://user-images.githubusercontent.com/29060552/56961727-20aa8280-6b72-11e9-8d48-69a44688fc87.PNG">

Hi I still see , graphs are not seen in chrome  73.0.3683.103

Also String videoLink = "<a href="+SauceVideoLink+" target='_blank' >Video</a>";
			scenario.embed(videoLink.getBytes(StandardCharsets.UTF_8), "text/html");

Dint work when i click on it.

**Comment by laxersaz** [comment]
This is very interesting since this is the first time I saw this issue and it was never reported before. Do you have any other software running that might block access to parts of the report?

For the link - is it rendered correctly? Did you inspect the HTML code of the report?
Also please share a JSON file (you can just replace sinsitive information with "xxxx" so I can test it with your exact data.

**Comment by rahulbommanaboina** [comment]
Link issue - Attached screenshot
![bug2](https://user-images.githubusercontent.com/29060552/56967257-7be27200-6b7e-11e9-9db9-0f0e9e43021a.png)


JSON Below:

[
  {
    "comments": [
      {
        "line": 1,
        "value": "# language: en"
      }
    ],
    "line": 3,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 11009919892,
              "status": "passed"
            },
            "match": {
              "location": "location1"
            }
          }
        ],
        "line": 11,
        "name": "name",
        "description": "",
        "id": "id",
        "after": [
          {
            "result": {
              "duration": 1255759132,
              "status": "passed"
            },
            "match": {
              "location": "location"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 696788672,
              "status": "passed"
            },
            "line": 12,
            "name": "name",
            "match": {
              "location": "pckge.steps()"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 2179202991,
              "status": "passed"
            },
            "line": 13,
            "name": "post the request body of address search api using below json elements",
            "match": {
              "location": "location1"
            },
            "rows": [
              {
                "cells": [
                  "address",
                  "103"
                ],
                "line": 14
              },
              {
                "cells": [
                  "city",
                  "Hyderabad"
                ],
                "line": 15
              },
              {
                "cells": [
                  "state",
                  "Telangana"
                ],
                "line": 16
              },
              {
                "cells": [
                  "zipCode",
                  "234234"
                ],
                "line": 17
              }
            ],
            "keyword": "And "
          },
          {
            "result": {
              "duration": 351634447,
              "status": "passed"
            },
            "line": 18,
            "name": "name2",
            "match": {
              "location": "steps()"
            },
            "rows": [
              {
                "cells": [
                  "desc",
                  "Testing"
                ],
                "line": 19
              }
            ],
            "keyword": "And "
          },
          {
            "result": {
              "duration": 15922805816,
              "status": "passed"
            },
            "line": 20,
            "name": "name3",
            "match": {
              "location": "location2"
            },
            "rows": [
              {
                "cells": [
                  "email",
                  "testing"
                ],
                "line": 21
              },
              {
                "cells": [
                  "Password",
                  "ENCRYPTED"
                ],
                "line": 22
              }
            ],
            "keyword": "And "
          },
          {
            "result": {
              "duration": 1731042364,
              "status": "passed"
            },
            "line": 23,
            "name": "name4",
            "match": {
              "arguments": [
                {
                  "val": "Testing3",
                  "offset": 49
                }
              ],
              "location": "step4"
            },
            "keyword": "Then "
          },
          {
            "result": {
              "duration": 61417194226,
              "error_message": "Assertion Failure",
              "status": "failed"
            },
            "line": 24,
            "name": "name5",
            "match": {
              "location": "steps6"
            },
            "rows": [
              {
                "cells": [
                  "Hobby",
                  "Cricket"
                ],
                "line": 25
              },
              {
                "cells": [
                  "SecondHobby",
                  "Music"
                ],
                "line": 26
              }
            ],
            "keyword": "When "
          },
          {
            "result": {
              "status": "skipped"
            },
            "line": 27,
            "name": "name9",
            "match": {
              "arguments": [
                {
                  "val": "Testing3",
                  "offset": 52
                }
              ],
              "location": "Steps8"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "line": 6,
            "name": "@UI"
          }
        ]
      }
    ],
    "name": "XXXXX",
    "description": "Test",
    "id": "id",
    "keyword": "Feature",
    "uri": "pathToFeatyre"
  }
]

**Comment by laxersaz** [comment]
I used your JSON with 1.10.2 and it all works - the pages are all rendered and displayed correctly.
Also, when I add a link as html, it is correct.
Do you have any more information about your system, where you run the reporting and anything else that might help debugging this?

**Comment by rahulbommanaboina** [comment]
Hi @Laxersaz , today i observed that , reports are being populated correctly in chrome when i run the code locally  , but when we run through jenkins , reports are not being populated correctly in chrome and not able to see the video.

**Comment by laxersaz** [comment]
Could this just be related to https://github.com/trivago/cluecumber-report-plugin/issues/98 ?
This is the Jenkins content policy.

**Comment by rahulbommanaboina** [comment]
May be but , we have set the system property to allow all policies as shown in the link shared by you. still showing same.
