### ISSUE TITLE
Add a section that visualizes parallel runs

### ISSUE THREAD

**Issue by laxersaz** [trivago/cluecumber-report-plugin#161]

**Comment by DeChrish** [comment]
@laxersaz  - Pl average the duration time; Currently we are running the test in parallel- Jenkins Job duration and Cucumber Report test duration is different.

Cucumber report test duration adds each parallel time and consolidates. For ex if i have 10 scenario which takes 2 mins to complete then Jenkins Jobs completed in ~2 mins/ But the Cucumber report says ~20mins

**Comment by laxersaz** [comment]
This was already tackled. If you use Cucumber JVM 4.3.0 or higher, this is supported since it introduced start timestamps. In other cases, it is not possible to determine which tests ran in parallel from the generated JSON. Just use version 1.10.2.

**Comment by DeChrish** [comment]
@laxersaz   I have attached 2 screen shot.

1. Cluecumebr report  -=  448m
2. Jenkins Report  -= 13m

<img width="1346" alt="Screen Shot 2019-05-13 at 1 43 32 PM" src="https://user-images.githubusercontent.com/6211294/57652805-39a92f80-7585-11e9-866d-967683e22827.png">
<img width="1559" alt="Screen Shot 2019-05-13 at 1 44 11 PM" src="https://user-images.githubusercontent.com/6211294/57652815-42016a80-7585-11e9-91ef-61a8161e37cd.png">

**Comment by DeChrish** [comment]
@laxersaz similar to #138. pl close this ticket

**Comment by laxersaz** [comment]
Hi @DeChrish ,
no this is not similar.
- #138 was about the time on the summary page
- #161 is about a dedicated section to visualize parallel runs (comparable to Cucumber's parallel report)

**Comment by jzaratei** [comment]
hello @laxersaz ! Any chance to get this features in the following releases?
Thanks for the great work!

**Comment by laxersaz** [comment]
This is already built into Cucumber, so no need for it in Cluecumber.
