### ISSUE TITLE
Tests that are Skipped using Cucumber's PendingException are marked as Passed

### ISSUE THREAD

**Issue by mjordanBetBright** [trivago/cluecumber-report-plugin#162]
**Description**
Tests that are skipped are being marked as passed. Tested on v1.10.1

**To Reproduce**

1. Run a suite where some tests will be skipped (in my case using Pending Exception for a step)
2. Open cluecumber index.html when completed

**Expected behavior**
The tests that are marked as skipped (using maven failsafe plugin) should be marked as yellow

**Actual behavior**
The tests that are skipped are marked as passed (green)

Not sure if this is expected or not. Could be a bug or a potential improvement? I notice that this was brought up [here](https://github.com/trivago/cluecumber-report-plugin/issues/70) but not entirely sure why a test that is skipped before completion should be marked as passed.

**Comment by mjordanBetBright** [comment]
Update: just discovered the failScenariosOnPendingOrUndefinedSteps configuration. Marking this as true marks my pending tests as failed, but setting it to false still shows them as passed?

My pom is attatched
`<plugin>
	<groupId>com.trivago.rta</groupId>
	<artifactId>cluecumber-report-plugin</artifactId>
	<version>1.10.1</version>
	<executions>
		<execution>
			<id>report</id>
			<phase>post-integration-test</phase>
			<goals>
				<goal>reporting</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
		<generatedHtmlReportDirectory>${project.build.directory}/generated-report</generatedHtmlReportDirectory>
		<failScenariosOnPendingOrUndefinedSteps>false</failScenariosOnPendingOrUndefinedSteps>
		<expandBeforeAfterHooks>true</expandBeforeAfterHooks>
		<expandStepHooks>true</expandStepHooks>
		<customParameters>
			<Custom_Parameter>XXXX</Custom_Parameter>
			<Custom_URL>XXXX</Custom_URL>
		</customParameters>
	</configuration>
</plugin>`

**Comment by laxersaz** [comment]
This is expected. A scenario is considered skipped when all steps are skipped. Since you have passing steps before it is considered passed. This is according to the official Cucumber guidelines.

**Comment by mjordanBetBright** [comment]
hmmm, seems like an odd guideline. But I'll take it into account when placing my PendingExceptions. Thanks for the reply, will close
