### ISSUE TITLE
Allowing Custom Parameters from file

### ISSUE THREAD

**Issue by gazler22** [trivago/cluecumber-report-plugin#166]
It would be nice to have the ability to load customParameters from a file as well into the report.

This allows for dynamically changing the custom parameters in the file (instead of having to update the pom) in multiple cases, for eg: when the Cucumber suite is being triggered from different builds, each having different data to show in the report.

**Comment by laxersaz** [comment]
This PR will be included in the next release. However, please note that dynamically setting custom parameter values is already possible without any pom modifications 😊

**Comment by gazler22** [comment]
Ah, could you tell me how?

And do we need this PR then?

**Comment by laxersaz** [comment]
https://github.com/trivago/cluecumber-report-plugin#passing-custom-parameters-via-command-line

**Comment by gazler22** [comment]
Ah, I think I missed this. But thank you :)

**Comment by laxersaz** [comment]
I will take a closer look at the PR on Monday and give feedback 😊

**Comment by laxersaz** [comment]
The more I think about this, the more doubts I am starting to have.
Reading properties from a file is already possible, e.g. with the http://www.mojohaus.org/properties-maven-plugin/ so this might be covered already.

**Comment by gazler22** [comment]
Yes, since we can already provide the property values to `customParameters` tag, i dont think this PR would be much useful for that.

I do think it can be useful in cases where you also want to provide the **Key** dynamically or have completely different properties to provide from different builds.

For eg:

**Build 1:**
```
<customParameters>
        <Param_Name1>This is a test</Param_Name1>
        <Param_Name2>http://www.google.com</Param_Name2>
</customParameters>

```

**Build 2:**
```
<customParameters>
        <Param_Name3>This is not a test</Param_Name3>
        <Param_Name4>http://www.abc.com</Param_Name4>
        <Param_Name4>Some other new value</Param_Name4>
</customParameters>
```

Here, if we have different builds which have different ParamNames to give or have extra data to provide
which other builds don't, they will be able to do it.

I am not sure tho, if it is also somehow possible to provide the **Names** for the parameters dynamically to the `customParameters` tag or to add new **Paramters** on the fly.

What do you think?

**Comment by laxersaz** [comment]
That's a good point. I will research if this is also possible via the Maven out-of-the-box solution.

**Comment by gazler22** [comment]
Sure :)
