### ISSUE TITLE
Steps containing Cucumber expressions are displayed correctly

### ISSUE THREAD

**Issue by laxersaz** [trivago/cluecumber-report-plugin#168]

**Comment by josepj** [comment]
@laxersaz, I see that the under **All Steps**, the steps are displayed as:
```
I log in to the "{}" environment as "{}"
```
and not:
```
I log in to the "test" environment as "user1"
```
The steps appear correctly in the scenario details page.

**Comment by laxersaz** [comment]
Hi! This is expected behavior for steps with placeholders because seeing the concrete steps including their values would be pretty pointless since each one would most likely only have one match.

**Comment by josepj** [comment]
Thanks @laxersaz. I think I misunderstood what was being displayed under that tab.
