### ISSUE TITLE
Customizing color of pie charts 

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#172]
Can the framework support the overriding of default colors of the pie-charts etc? Can take inputs in terms of color names, rgb or hex. This option could be added to the existing custom.css.

**Comment by laxersaz** [comment]
This is not possible at the moment. I will add this as a feature in the next release.

**Comment by grasshopper7** [comment]
Can the title of the report also be made customizable?

**Comment by laxersaz** [comment]
Keep the ideas coming - I like this!

**Comment by grasshopper7** [comment]
Currently one can configure the output directory using `generatedHtmlReportDirectory`.  Is it possible to add a  valid date time  pattern to this?  For example
`<generatedHtmlReportDirectory>${project.build.directory}/yyyy MM dd report </generatedHtmlReportDirectory>` 
will create a report folder like `2019 06 16 report`.

Easier identification of old reports. Saves effort.

**Comment by grasshopper7** [comment]
Can the datetime formats for the times inside the report made configurable?

**Comment by grasshopper7** [comment]
Not sure if this is an issue. In both the cases when 'All Scenarios' and 'Scenario Sequence' are selected always 'Scenario Summary' is highlighted.  Seems a bit confusing.

index.html -> All Scenarios
![index-header](https://user-images.githubusercontent.com/10829355/59567645-bf8d2e80-908d-11e9-83d6-6d33ae90c737.png)

scenario-sequence.html -> Scenario Sequence
![sequence-header](https://user-images.githubusercontent.com/10829355/59567654-d6338580-908d-11e9-820e-8876c4ab3c6e.png)

**Comment by grasshopper7** [comment]
In 'All Scenarios' page (index.html), is it possible to have a collapse\expand option for the status sections (failed, skipped, passed). Saves effort of scrolling if there are multiple failures or skips to get to other sections below them.

**Comment by laxersaz** [comment]
I created separate issues for this. Please also do this in the future for new ideas :-)

**Comment by grasshopper7** [comment]
Will do. Thanks.

**Comment by laxersaz** [comment]
Done in version 2.1.0 - work in progress.
