### ISSUE TITLE
Can the title of the report be made customizable?

### ISSUE THREAD

**Issue by laxersaz** [trivago/cluecumber-report-plugin#176]
Can the title of the report also be made customizable?

_Originally posted by @grasshopper7 in https://github.com/trivago/cluecumber-report-plugin/issues/172#issuecomment-502438719_

**Comment by laxersaz** [comment]
Do you mean the title of the page that appears in the browser tab?

**Comment by grasshopper7** [comment]
Yes - "Cluecumber Report"

**Comment by laxersaz** [comment]
Done in version 2.1.0 - work in progress.
