### ISSUE TITLE
Expandable area for 'Steps' bar chart

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#180]
Can the area of the 'Steps' bar chart increased or made expandable. The number of steps in the project can be quite large and the bar chart will get cluttered pretty quick.
I simulated the case for the 'Tags' chart (well it was easier to do). There are 29 tag entries and it is crowded.
![step-crowd](https://user-images.githubusercontent.com/10829355/59623344-8e763200-9151-11e9-9b8d-18abd1e53cad.png)

Maybe look at :
1. Increase the area of the chart by collapsing the summary on the right .
2. User has options to select the status or combination of status to display. If the steps are above a threshold number show the steps with failures and skips by default.

**Comment by laxersaz** [comment]
I increased the chart areas for tag, step and feature summary pages for version 2.1.0 (work in progress)
