### ISSUE TITLE
Change "skipped" name

### ISSUE THREAD

**Issue by raamojirao** [trivago/cluecumber-report-plugin#182]
This is a great reporting tool.Thanks for that. In the reports that are generated I would like to change the word "skipped" to something else eg: "Skipped" scenarios to "Rerun" scenarios. How could I do this. Please suggest

**Comment by laxersaz** [comment]
Since the skipped status is calculated based on the real cucumber status, it would not make sense to call it anything else. The premise of Cluecumber is that it works with the standard Cucumber json format.
Maybe I mistunderstand why you want to change this wording...
