### ISSUE TITLE
Add custom text to report

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#183]
Can an option be created to add custom text to a report? Similar to adding custom properties option. Maybe this could be added to the same area where the properties are displayed.

Allows one to mention any remarks or details about the test run.

**Comment by laxersaz** [comment]
What would be the difference between adding a custom property with a long value and adding a custom text?

**Comment by grasshopper7** [comment]
Custom property needs me to add a key. This would give an option of adding mutli-line text without the requirement of a key in configuration or the key displayed in the report.

**Comment by laxersaz** [comment]
Done in 2.1.0 - work in progress:

![image](https://user-images.githubusercontent.com/5775857/60034191-55d2dd00-96aa-11e9-97a4-14146713b92d.png)

**Comment by grasshopper7** [comment]
Waoh! that was quick
