### ISSUE TITLE
Need help on html report generation

### ISSUE THREAD

**Issue by jayanthktn** [trivago/cluecumber-report-plugin#185]
I really need help in generating html report, i did pom configurations and run.test file but i am not able to see the reports in the corresponding target folders. please help me with this. Attached the screenshot of them. please help me
![image](https://user-images.githubusercontent.com/27004220/60242639-bc870f00-98d3-11e9-9682-e9be8d1a21e7.png)
![image](https://user-images.githubusercontent.com/27004220/60242671-d4f72980-98d3-11e9-8c8f-92cd12bd688d.png)

**Comment by laxersaz** [comment]
Don't use the `html` plugin in your Cucumber runner - this is a completely different reporting. Cluecumber is a Maven plugin that is independent of the runner.
How do you run your tests?

Please also try the Cluecumber example project first to get an understanding of how to use it.

**Comment by jayanthktn** [comment]
I ll try and let you know. Thanks for the response. And I am running
directly the run class.



Thanks
Jayanth

வியா, 27 ஜூ, 2019, 1:28 PMக்கு, Benjamin Bischoff <notifications@github.com>
எழுதியது:

**Comment by jayanthktn** [comment]
@laxersaz I tried but not generated.
![image](https://user-images.githubusercontent.com/27004220/60252284-99665a80-98e7-11e9-9768-318a37da9a05.png)

**Comment by laxersaz** [comment]
Like I said, it has to be run via Maven. If you only run your run class, this is not using Maven...

**Comment by jayanthktn** [comment]
Sorry to ask this again, please provide me your executable sample project so that i can refer. @laxersaz

**Comment by jayanthktn** [comment]
Steps i have done : 
1] Created maven project,
2] Added above pom dependencies,
3] Created simple testcases with runner class.
4] Executing with "mvn test".
If i miss anything, let me know and also kindly share any sample project i can clone and run in my local. @laxersaz 


Thanks for your time.

**Comment by grasshopper7** [comment]
@jayanthktn You need to run using "mvn verify". You should check this [page](https://github.com/trivago/cluecumber-report-plugin/tree/master/example-project). Also the "Run" runner will not be picked up automatically by Surefire unless u rename it to "RunTest" or include it explicitly. Refer to [this](https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html).

**Comment by laxersaz** [comment]
Thanks @grasshopper7

**Comment by laxersaz** [comment]
@jayanthktn is it clear now?

**Comment by jayanthktn** [comment]
@laxersaz I didn't get what you are saying. sorry. still, I am not able to use your pleasant report.

**Comment by laxersaz** [comment]
Hi! This is a known bug that was fixed with version 2.0.1
So if you update the Cluecumber version to this one it should work.

**Comment by jayanthktn** [comment]
@laxersaz Thanks bro, version 2.0.1 working fine.
