### ISSUE TITLE
Support report in pdf format

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#187]
Is it possible to look at the option of generating the report in pdf format? Maybe the pie and bar charts. Mention just the failed and skipped scenarios if they exist.

**Comment by laxersaz** [comment]
I started looking into this :-)
Let's see if this is doable.

**Comment by grasshopper7** [comment]
Not sure if this is a sound suggestion without understanding the code. But here goes. You have a pretty solid parsing logic for the json. And a great html report. How about

**Comment by laxersaz** [comment]
Woah! This is a big suggestion :-)

**Comment by josepj** [comment]
Referring to this [comment](https://github.com/trivago/cluecumber-report-plugin/issues/175#issuecomment-503152036) in #175, you can use the `Show` option in the report to show all the failures (upto 100) in a single page, and then easily save the report as a pdf file directly from the browser. Or am I missing something here?

**Comment by laxersaz** [comment]
Well what I would like to ultimately have is a PDF report with internal links. But let's see if that's feasible.

**Comment by grasshopper7** [comment]
When the 'passed' scenarios are toggled to OFF, the 'passed' scenarios also disappear from the pie chart. So it does not portray the total run results. Then it requires a longer workaround to include the complete details.
There other minor things like search, sorting, entries functionalities etc which are redundant in pdf format.

**Comment by josepj** [comment]
> Well what I would like to ultimately have is a PDF report with internal links. But let's see if that's feasible.

@laxersaz, that will be fantastic if it is feasible! 
Actually, I did have a similar requirement and was here to request a feature, when I saw @grasshopper7's request. 😃  I was asked to email the test report recently and could not find a way to do it other than zipping and attaching the report folder. I tried saving the report as a `.mht` file and tried the [SingleFile](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle?hl=en) chrome plugin, but neither worked.

An emailable report, pdf or single page HTML with internal links, would be a great addition.

**Comment by GregJohnStewart** [comment]
Bump to this, would be great to see! Perhaps even having a "Printable" output/page would be acceptable, then users could simply print the page to pdf

**Comment by laxersaz** [comment]
I am currently working on the completely new Cluecumber from the ground up. I will keep this in mind.

**Comment by gitissuepost** [comment]
> 

@bischoffdev Is the new version you are referring available under a sperate project? or is it too soon for this?

**Comment by bischoffdev** [comment]
This version is still in a very early draft since I was away from the job for quite a while. So I cannot really give any estimation here.

**Comment by bischoffdev** [comment]
This will most likely not be included in Cluecumber since its main purpose is the generation of html reports.
