### ISSUE TITLE
Make plugin logging configurable

### ISSUE THREAD

**Issue by laxersaz** [trivago/cluecumber-report-plugin#189]
> I wonder if we can stop generation of below logs from report in console:
> 
> * source JSON report directory     : /Users/nauman.shahid/Nauman-data/Dev_Home/sbir.automation/target/cucumber-report
>   [INFO] - generated HTML report directory  : /Users/nauman.shahid/Nauman-data/Dev_Home/sbir.automation/target/Automation-Report
>   [INFO] ------------------------------------------------------------------------
>   [INFO] - custom parameter                 : Test Automation Framework
>   [INFO] - custom parameter                 : Environment -> qa
>   [INFO] ------------------------------------------------------------------------
>   [INFO] - fail pending/undefined scenarios : false
>   [INFO] - expand before/after hooks        : false
>   [INFO] - expand step hooks                : false
>   [INFO] - expand doc strings               : false
>   [INFO] - page title                       : Automation Report
>   [INFO] - custom CSS file                  : css/custom.css
>   [INFO] - colors (passed, failed, skipped) : #28a745, #dc3545, #ffc107

(Created from #188)

**Comment by Naumansh** [comment]
Great... looking forward to get it asap . !!!!

**Comment by Naumansh** [comment]
@laxersaz is it completely off need to pass some parameter in plugin ?

**Comment by Naumansh** [comment]
got it from readme
