### ISSUE TITLE
Cucumber Data Table is not showed in Scenario Details

### ISSUE THREAD

**Issue by JoVzla** [trivago/cluecumber-report-plugin#19]
### Expected behavior
```
Step 2   Then Log in to your account with     | Username | username |    0m 09s 662ms  passed
                                                 | Password | 123456   |                                       
                                                                       
```

### Actual behavior
`Step 2   Then Log in to your account with         0m 09s 662ms       passed`

### Reproduction steps

```
Feature:  Login: Login Test Feature

  Scenario: Login to account
    Given Open Site
    Then Log in to your account with
      | Username | username |
      | Password | 123456      |
```

**Comment by laxersaz** [comment]
Hi @JoVzla 
Could you please send me an example JSON file that includes a data table for reference?

**Comment by JoVzla** [comment]
Done!

[AffiliateUrl_scenario001_run001_IT.json.zip](https://github.com/trivago/cluecumber-report-plugin/files/1632378/AffiliateUrl_scenario001_run001_IT.json.zip)

**Comment by laxersaz** [comment]
Thanks a lot, I am currently looking into this issue.

**Comment by laxersaz** [comment]
Will be fixed in release 0.2.0

**Comment by laxersaz** [comment]
@JoVzla Version 0.2.0 is now available that adds data table support. The tag functionality will be done in the next release.

**Comment by JoVzla** [comment]
Thanks! Downloading and testing.
