### ISSUE TITLE
Screenshots are not being embedded to my cluecumber report

### ISSUE THREAD

**Issue by niamhmccann** [trivago/cluecumber-report-plugin#190]
Screenshots are not being added to the report - I have added configurations I could see online but I am not seeing the button to show/hide the before/after hooks.

![image](https://user-images.githubusercontent.com/17048530/60826881-cef02b00-a1a6-11e9-9df2-2a9b0f5dfc9f.png)

**Comment by laxersaz** [comment]
Hello! Without an example json file, I cannot see where your screenshot should be embedded. Are you sure screenshots are being taken correctly and attached to the scenario by your test framework?

**Comment by jzaratei** [comment]
hi! maybe the screemshot is embedded in your hooks. In that case click on Show scenario hooks.

![image](https://user-images.githubusercontent.com/47472889/60971574-c58ccd00-a324-11e9-9c7c-738b7a325851.png)

**Comment by laxersaz** [comment]
If you want to keep the before and after hooks always open, just add this configuration parameter:

```
<expandBeforeAfterHooks>true</expandBeforeAfterHooks>
```

**Comment by laxersaz** [comment]
@niamhmccann , did this solve your problem?

**Comment by laxersaz** [comment]
Closed due to no reaction.
