### ISSUE TITLE
Overcounting of step usage in All Steps

### ISSUE THREAD

**Issue by Naumansh** [trivago/cluecumber-report-plugin#192]
Under the "All Steps" tab of the report the "Step Summary Result Chart" y-axis is marked as "Number of Scenarios". This would imply that it is showing how many scenarios a step is used in. However, if a step is used multiple times in a scenario it is counted multiple times, leading to unexpectedly skewed data.

Possible Solutions:
Each step should be counted once for each scenario
The y-axis should be relabeled to "Number of Usages"

**Comment by laxersaz** [comment]
I renamed the y axis to number of usages since a step could potentially be included multiple times in a scenario with different results.

**Comment by laxersaz** [comment]
Will be included in 2.2.0

**Comment by Naumansh** [comment]
@laxersaz Thanks man !! Tentative time frame for 2.2.0 ?

**Comment by laxersaz** [comment]
Releasing now :-)

**Comment by Naumansh** [comment]
hahah...great thanks buddy !!
