### ISSUE TITLE
Skipped steps count shown as zero

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cluecumber-report-plugin#197]
**Describe the bug**
Skipped Steps count shown as zero.

**To Reproduce**
1. Run scenarios in parallel
2.Due to previous step failure remaining steps in scenario are skipped 
3. Go to report to check count of skipped steps 
4. Expected: the count of passed, failed and skipped steps should be displayed on step summary page 
Actual: "All scenario" counts are shown in step summary page  (please refer attached screenshot

**Attachments**
Attached
![skipped steps](https://user-images.githubusercontent.com/22300715/61963175-0b8a9780-af99-11e9-8228-a50978f7ec54.jpg)

Note: Graphs are cluttered (x and Y axis) if number scenarios are more in test suite (please refer attached screenshot)
**Additional context**

**Comment by laxersaz** [comment]
The counts on the right side refer to the 63 scenarios not the steps. So this is actually correct. Since no __scenario__ is skipped the __0__ is legitimate.
