### ISSUE TITLE
Discrepancy in display of total run time in reports

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cluecumber-report-plugin#198]
**Describe the bug**
Discrepancy in display of total run time in reports
**To Reproduce**
1. Run a Small Test suite to verify the total run time 
2. after execution note the total time from the execution log
3. go to clucumber report and note the total time for execution and compare with the above step.
4. See below screenshot
**Actual behaviour**
total runtime displayed on the report is sum of runtime of all the scenarios
**Expected behavior**
Good to have parallel runtime on the reports apart from sum of the runtime.
![Totaltime](https://user-images.githubusercontent.com/22300715/61965132-85248480-af9d-11e9-9ebf-7679fb981114.png)

**Attachments**
If applicable, add screenshots or sample JSON files to help explain your problem.

**Additional context**

**Comment by laxersaz** [comment]
If you use a newer Cucumber jvm, this will display the parallel runtime since its generated json contains timestamps for each scenario. In older versions, there is no information about when a scenario actually ran - that's why you get the total time instead.

**Comment by Srinivasaraor** [comment]
Thanks for the input.
I have updated the Cucumber-Jvm to latest version, now i could able to see the parallel run time on clucumber reports.
![image](https://user-images.githubusercontent.com/22300715/62061366-06c21f80-b1f5-11e9-9eeb-c6298dbc019c.png)

**Comment by Srinivasaraor** [comment]
Thank you Very much Benjamin Bischoff! 

Closing the issue

**Comment by Srinivasaraor** [comment]
i am still seeing little difference in test run time - Please find the screens below

![image](https://user-images.githubusercontent.com/22300715/62067839-a934cf80-b202-11e9-9bb4-7109cf6f6795.png)

![image](https://user-images.githubusercontent.com/22300715/62067937-f022c500-b202-11e9-982d-3c5de7b099a1.png)

**Comment by laxersaz** [comment]
Well the report looks only at the tests that were run and not the total build time (which is shown in your screenshot of the console output). Depending on what is being done during the build this naturally takes longer than the test runs.
If you look at the start and end time in the report, it is correct.

**Comment by Srinivasaraor** [comment]
Thanks for details explanation.
