### ISSUE TITLE
Remove unnecessary eval JavaScript call

### ISSUE THREAD

**Issue by jonmbake** [trivago/cluecumber-report-plugin#199]
**Describe the bug**
The generated report contains JavaScript code that invokes [eval()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval): https://github.com/trivago/cluecumber-report-plugin/blob/2.2.0/plugin-code/src/main/resources/template/snippets/js.ftl#L53. `eval` is considered a security risk and the way it is being used is unnecessary.

**To Reproduce**
Look at generated HTML report.

**Expected behavior**
Remove `eval` call.

**Attachments**
N/A

**Additional context**
https://security.stackexchange.com/questions/94017/what-are-the-security-issues-with-eval-in-javascript

**Comment by laxersaz** [comment]
Thanks for taking the time to report this. I will fix this in the next release.

**Comment by laxersaz** [comment]
Fix ready to release in 2.3.0
