### ISSUE TITLE
Improvement:   Graphics by tags

### ISSUE THREAD

**Issue by JoVzla** [trivago/cluecumber-report-plugin#20]
### Expected behavior
Graphics to see errors/success by tags, making easy to see what component is failing 

### Actual behavior
Right now tags add no value to the report

**Comment by laxersaz** [comment]
Do you mean a page like in cucumber-reporting?

https://raw.githubusercontent.com/damianszczepanik/cucumber-reporting/master/.README/tag-overview.png

**Comment by JoVzla** [comment]
Hi, yes is too usefull!

**Comment by laxersaz** [comment]
On it. I hope to have a view ready to be released together with 0.5.0

**Comment by laxersaz** [comment]
I am working on this feature and I hope I will have something usable soon.

**Comment by laxersaz** [comment]
Tag view will be in 0.5.0, planning to release today.
