### ISSUE TITLE
MissingFileException: File '' could not be found while mvn cluecumber-report:reporting run

### ISSUE THREAD

**Issue by mstas1993** [trivago/cluecumber-report-plugin#201]
**Describe the bug**
Caused by: com.trivago.cluecumber.exceptions.filesystem.MissingFileException: File '' could not be found while mvn cluecumber-report:reporting run
**To Reproduce**
1. Add based plugin to pom <plugin>
                <groupId>com.trivago.rta</groupId>
                <artifactId>cluecumber-report-plugin</artifactId>
                <version>2.0.0</version>
                <executions>
                    <execution>
                        <id>report</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>reporting</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
                    <generatedHtmlReportDirectory>${project.build.directory}/cluecumber-report</generatedHtmlReportDirectory>
                </configuration>
            </plugin>

2. Run tests and get .json result
3. Run  mvn cluecumber-report:reporting 

Result: Go to the screen

![2019-09-18_1825](https://user-images.githubusercontent.com/43540101/65162837-92f90200-da42-11e9-92ae-37b5daabca88.png)

**Comment by mstas1993** [comment]
I can be wrong with my settings and I will be grateful for the help.

**Comment by laxersaz** [comment]
Hi! This issue was fixed in version 2.0.1 but you are using the one before. 
By the way, the most recent version is 2.2.0 🙂

**Comment by mstas1993** [comment]
It works! Thanks a lot!
