### ISSUE TITLE
Properties passed via command line do not override the properties in POM

### ISSUE THREAD

**Issue by jaskaran0001** [trivago/cluecumber-report-plugin#202]
I want to generate the report using command line at a different path than the one mentioned inside pom.xml

Using the below command it should generate the report in D:\report folder but instead it is generating in the foldern mentioned inside pom file:
`mvn cluecumber-report:reporting -DsourceJsonReportDirectory=C:\example-project\target\cucumber-report -DgeneratedHtmlReportDirectory=D:\report`

POM configuration:
`			    <configuration>
			        <sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
			        <generatedHtmlReportDirectory>${project.build.directory}/generated-report</generatedHtmlReportDirectory>
			    </configuration>    `

Is there any way to achieve this?

**Comment by laxersaz** [comment]
Hi, yes there is. It is also mentioned in the documentation:
https://github.com/trivago/cluecumber-report-plugin#passing-properties-via-command-line

You need an extra property in your pom to achieve that.

**Comment by laxersaz** [comment]
Closed due to no reaction.
