### ISSUE TITLE
Report is not generated when running from Junit runner

### ISSUE THREAD

**Issue by sseenivasan89** [trivago/cluecumber-report-plugin#207]
how to run from Junit runner to generate report ?

`@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"json:target/cucumber-report/cucumber.json"},
				features = {"src\\test\\resources\\Test.feature"},
				glue = {"Steps" }, dryRun = false, monochrome = true)
public class TestRunner {
	
}`

`<plugin>
				<groupId>com.trivago.rta</groupId>
				<artifactId>cluecumber-report-plugin</artifactId>
				<version>2.3.1</version>
				<executions>
					<execution>
						<id>report</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>reporting</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<customParameters>
						<Custom_Parameter>Smoke Result</Custom_Parameter>
					</customParameters>
					<sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
					<generatedHtmlReportDirectory>${project.build.directory}/generated-report</generatedHtmlReportDirectory>
				</configuration>
			</plugin>`

**Comment by laxersaz** [comment]
Since Cluecumber is a Maven plugin, you need to run your tests using Maven.

**Comment by sseenivasan89** [comment]
if i run mvn test from cmd the report is not getting generated, it get generated when i use - mvn cluecumber-report:reporting, when i run this the test is not running but report is generated.

**Comment by laxersaz** [comment]
The `mvn test` lifecycle does not trigger the integration test phase that you have specified in your pom for Cluecumber. If you run `mvn verify` it does.

Please also check the example project: https://github.com/trivago/cluecumber-report-plugin/tree/master/example-project

**Comment by sseenivasan89** [comment]
mvn verify is working and generating report if my test pass, if my test fails it does not generate reprot

**Comment by laxersaz** [comment]
This is the standard Maven behavior. Please check https://github.com/trivago/cluecumber-report-plugin/issues/49

**Comment by AaronQudini** [comment]
@sseenivasan89 you can use `-Dmaven.test.failure.ignore=true` to get around this issue.

**Comment by laxersaz** [comment]
Yes you can. However, your build will always pass in this case.

**Comment by laxersaz** [comment]
Closed due to no further reaction.
