### ISSUE TITLE
[How to] Jenkins - any means to show test failures?

### ISSUE THREAD

**Issue by gheeno** [trivago/cluecumber-report-plugin#209]
Goal : 
To see if any test failed at a glance without viewing the report.

I know that we need to complete the mvn build cycle for the report to be generated. Meaning the build theoretically will always "pass". And to know the failure we would need to open the report.

Is there a way for me to configure the build runner to show if a test failed? without opening the report.

**Comment by laxersaz** [comment]
You can choose what to do with your build if you set up your Maven goals differently.

You could
- implement a custom Maven Enforcer rule to pass or fail the build based on the test results or
- run the reporting phase separately from your test lifecycle (in a Jenkins pipeline you could do it in a `finally` block so it always executes).

Also you can implement some logging/messaging/hook to see the failures without looking at the report. This is beyond the scope of Cluecumber though.

**Comment by gheeno** [comment]
Pardon the ignorance, 
If I opt for option 1: `implement a custom Maven Enforcer rule to pass or fail the build based on the test results`

It would still complete the lifecycle and generate the report but Jankins build icon would be red I reckon?

**Comment by laxersaz** [comment]
Exactly :-)

**Comment by gheeno** [comment]
Hi there - I have used the JUnit Plugin instead to notify me of the failures. 
This would have completed the mvn lifecycle without introducing new code. 

Thank you!

You can close this thread.
