### ISSUE TITLE
Forward slashes in cucumber tags causes file creation error

### ISSUE THREAD

**Issue by wvbrandt** [trivago/cluecumber-report-plugin#210]
**Describe the bug**
Since I need to haul cucumber tests out of Jira and lay them down in particular places before testing starts, I embed tags in the cucumber scenarios to the indicate where the files should go. So for example with the tag, "@Location-M_SysUpdater/MH_SysUpdaterDeleteEnterprise", the "@Location-" would be stripped and the file laid down in the path "M_SysUpdater/MH_SysUpdaterDeleteEnterprise.feature". Afterwards when Cluecumber goes to generate a report by tag name, it tries to build a path from the tag name, isn't expecting another path, and promptly dies.

**To Reproduce**
1. Use a tag with a forward slash in a cucumber scenario and run the test
2. Execute cluecumber afterwards
3. Note the error:
[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.10.2:reporting (default-cli) on project cucumber: File '/home/jenkins/workspace/sam-cucumber-testing/target/sam-html-report/pages/tag-scenarios/tag_Location-M_SysUpdater/MH_SysUpdaterDeleteEnterprise.feature.html' could not be created.

**Expected behavior**
Tags including forward slashes should be laundered by replacing the slashes with underscores or removing them altogether.

**Attachments**
Stack trace.
[stacktrace.log](https://github.com/trivago/cluecumber-report-plugin/files/3865882/stacktrace.log)

**Additional context**
Run with Cluecumber 1.10.2. I'm updating to see if this has been addressed in the latest version.

**Comment by laxersaz** [comment]
The latest Cluecumber version is 2.3.1 not 1.10.2 by the way. It is always shown in the badges in github.

**Comment by laxersaz** [comment]
Is this still occuring?

**Comment by laxersaz** [comment]
Related bug: #231
So closing this one in order to not get confused 😸

**Comment by Labouh** [comment]
Regarding issue #231, it is not exactly the same bug, even if it can be solved together.

In my case the report is generated *but* the link is broken, here there is a exception!
