### ISSUE TITLE
How can I embed Screenshots or logs in the cluecumber report?

### ISSUE THREAD

**Issue by prasanth-krishtin** [trivago/cluecumber-report-plugin#214]
I just need to embed Screenshots or logs in the cluecumber report. can you please help me?

**Comment by laxersaz** [comment]
Hi! It depends on your test framework. Cluecumber takes all attachments from the generated Cucumber JSON. So whatever you attach to your scenario during your test run is visible in Cluecumber.

**Comment by sudgarre** [comment]
@laxersaz : I have added an @after cucumber hook & placed my code for taking screenshots. I then ran my tests in parallel using surefire plugin & generate reports using cluecumber plugin. 

I noticed that the screenshots are not attached in the cluecumber report but the screenshots are available on the cucumber pretty reports. Please help

**Comment by laxersaz** [comment]
Hi! The screenshots are probably there but you didn't expand the after hooks. Please check out this issue and the solution :-)

https://github.com/trivago/cluecumber-report-plugin/issues/190

**Comment by sudgarre** [comment]
@laxersaz : This did the trick, Thanks muck !
