### ISSUE TITLE
Can we set All Features to be default starting page?

### ISSUE THREAD

**Issue by djolexinc** [trivago/cluecumber-report-plugin#217]
**Is your feature request related to a problem? Please describe.**
Having more features makes browsing on starting page slow and awful.

**Describe the solution you'd like**
Can we have feature-summary.html as starting page? Or where can i change it locally?

**Describe alternatives you've considered**
I have tried searching for that option, but there is none.

**Comment by djolexinc** [comment]
This can be really nice feature to have in pom.xml file, something like <customStartingPage> configuration.

**Comment by laxersaz** [comment]
Very nice feature, I will add this to the next release in 2020.

**Comment by djolexinc** [comment]
Thank you sir.

**Comment by laxersaz** [comment]
This already existed since May.
