### ISSUE TITLE
Generate Cluecumber reports for cucumber rerun option with parallel execution

### ISSUE THREAD

**Issue by sudgarre** [trivago/cluecumber-report-plugin#218]
I am currently using the approach to rerun failed tests (tests are rerun only once) using two runner files but i am finding difficult to generate reports using cluecumber reports plugin for both initial & rerun scenarios.

Please can you share an option where cluecumber reports are generated even when both the initial & rerun fails.

**Comment by laxersaz** [comment]
I don't quite get your problem. If you want to always generate the report regardless of the run/rerun status, you can run the reporting as a completely separate Maven command after both executions are done. Or you can use the failsafe option `<testFailureIgnore>true</testFailureIgnore>` that ignores failed tests and continues in the Maven lifecycle. If you want to fail the build afterwards, you need to implement a custom Maven enforcer rule that checks the results of your runs and reruns.

**Comment by laxersaz** [comment]
Closed due to no reaction.
