### ISSUE TITLE
travis_wait to prevent travis build time out

### ISSUE THREAD

**Issue by FanJups** [trivago/cluecumber-report-plugin#219]
**Describe the bug**
My suggestion is related to a bug that might happen : [preventing a travis build time out](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) .

To do this, just add **travis_wait** as follows in **.travis.yml** : 

```
language:
  java

before_script:
  - cd plugin-code
  - travis_wait pip install --user codecov

after_success:
  - codecov
```

**Comment by laxersaz** [comment]
This never happened before because the build time is really short for this project.
Thanks for your suggestion - I will consider this for future projects.
