### ISSUE TITLE
Report is not generating if test case fails

### ISSUE THREAD

**Issue by tukaram57** [trivago/cluecumber-report-plugin#220]
Reporting goal is not getting executed if test phase fails.  

To reproduce-
fail any test case in test phase. this will terminate all maven process and report generation phase(package) will never get executed.  

Report should be generate no mater what is the status of test case(pass/fail).

**Comment by djolexinc** [comment]
Hello,
Have you tried changing phase settings in POM file?
I have put it to be <phase>test</phase>and it generates report. (When i run it with mvn clean test)

**Comment by tukaram57** [comment]
Hi, 

Just tested it with test phase in plugin, for me it didnt work out. no reports generated on failures. 
Only one way to avoid is ignore test failures in maven itself but I want to fail build in case of test failures but still want to have reports generated.

**Comment by laxersaz** [comment]
Please check this:
https://github.com/trivago/cluecumber-report-plugin/issues/49

**Comment by laxersaz** [comment]
Closed due to no reaction.
