### ISSUE TITLE
Please provide teamCity plugin for cluecumber report

### ISSUE THREAD

**Issue by sumitpahwa18** [trivago/cluecumber-report-plugin#225]
Please create teamcity plugin for cluecumber report

**Comment by laxersaz** [comment]
Hi, if this is related to your bug report #224 - this is most likely an issue with an insufficient Maven version and will probably not require a dedicated TeamCity plugin. As I am not familiar with TeamCity at all, feel free to contribute such a plugin. I will be happy to review it.

**Comment by laxersaz** [comment]
This was not an issue with TeamCity but with the Maven version :-)
