### ISSUE TITLE
Make screenshots and texts within the steps collapsible

### ISSUE THREAD

**Issue by Vijayabaskar03** [trivago/cluecumber-report-plugin#227]
**Is your feature request related to a problem? Please describe.**
The screenshots and texts are currently shown in a relatively large size and could take up a lot of page space when there are multiple screenshots.

**Describe the solution you'd like**
It would be nice if the screenshots and texts are collapsible so that only the steps would be shown in the default view and one can click through to look at the screenshots. 

**Describe alternatives you've considered**
I tried achieving this through custom CSS without any success.

**Comment by grasshopper7** [comment]
I was kinda looking for the same thing to display the screenshot as a thumbnail, which expands on selection. Similarly to display one line of text and option to expand for the complete text.

**Comment by laxersaz** [comment]
I'll see what I can do. There were more pressing things to do.

**Comment by GregJohnStewart** [comment]
Bumping this thread, I would really like to see this functionality.

**Comment by laxersaz** [comment]
I don't have time to work on this project at the moment. It is a good feature though, that you can add in a PR if needed soon.

**Comment by bischoffdev** [comment]
This is included in 2.8.0
