### ISSUE TITLE
Add id in html block to better usage of custom css

### ISSUE THREAD

**Issue by Labouh** [trivago/cluecumber-report-plugin#228]
**Is your feature request related to a problem? Please describe.**
There is a way to have a custom.css (customCss parameter) BUT it is difficult to change a specific block in the generated html because the class are always the same (row)

**Describe the solution you'd like**
Adding some id in the html code would allow better management of the different blocks

**Comment by Labouh** [comment]
I will do a pull-request on this easy subject

**Comment by laxersaz** [comment]
Release 2.3.2

**Comment by Labouh** [comment]
the release 2.3.2 is not available maven repo: https://mvnrepository.com/artifact/com.trivago.rta/cluecumber-report-plugin 

Do you publish it?

**Comment by laxersaz** [comment]
It is already available in Maven Central.
https://repo1.maven.org/maven2/com/trivago/rta/cluecumber-report-plugin/
