### ISSUE TITLE
Use folder names of feature files in report

### ISSUE THREAD

**Issue by Labouh** [trivago/cluecumber-report-plugin#230]
**Is your feature request related to a problem? Please describe.**
When you have a lot of feature files it is mandatory to dispatch them in different folders and subfolders. This is reflected in json files in uri value but not shown at all in cluecumber report :(
**Describe the solution you'd like**
Add a new tab in the report to show folders and subfolders, it could be named "requirements" as it is IMHO the good way to dispatch feature files...

**Comment by Labouh** [comment]
Seems link to #148

**Comment by laxersaz** [comment]
Right it is linked so I will close this one. Thanks for reporting, though.
