### ISSUE TITLE
Link is broken if a tag contains "special" character

### ISSUE THREAD

**Issue by Labouh** [trivago/cluecumber-report-plugin#231]
**Describe the bug**
When a tag contains an accent char like "@çà" the generated report is wrong:
* The html tag_ file does not gave the correct name (but the # code of the char, in my sample : tag_&#195;&#167;&#195;&#160;&#195;&#169;.html) 
* the link is also wrong : cluecumber-report/pages/tag-scenarios/tag_Ã§Ã%C2%A0Ã©.html

**To Reproduce**
1. In the example-project, edit a json file to set the tag @çà
2. Regenerate the report
3. Navigate to a scenario with the tag
4. Click on a tag will produce a page not found

**Expected behavior**
Tag should be well manage even if they are not ASCII code

**Comment by laxersaz** [comment]
Related to #210. Keeping this one open as a bug reference.

**Comment by laxersaz** [comment]
Fixed in 2.3.3
