### ISSUE TITLE
Add feature filename in the report

### ISSUE THREAD

**Issue by Remi68270** [trivago/cluecumber-report-plugin#233]
**Is your feature request related to a problem? Please describe.**
It is difficult to retrieve a scenario when reading the report

**Describe the solution you'd like**
Add the feature filename when displayed a scenario or a feature to facilitate maintenance.

**Comment by laxersaz** [comment]
Nice idea, will add this for sure.

**Comment by laxersaz** [comment]
Done in v2.5.0
