### ISSUE TITLE
improve scenario readability

### ISSUE THREAD

**Issue by Remi68270** [trivago/cluecumber-report-plugin#234]
**Is your feature request related to a problem? Please describe.**
In scenario steps, keywords are not different from the rest of the text and parameters are in strong style, that makes difficult a change throw css 

**Describe the solution you'd like**
Have a specific css style for keywords and parameters allowying to make them appear as prefered (color, bold....) with custom css.
I think, by default,  keyworkd should be in bold and parameter in italic, but it is only a question of opinion...

**Comment by laxersaz** [comment]
ready for release.

**Comment by laxersaz** [comment]
Released as 2.3.4
