### ISSUE TITLE
Undefined steps are shown as failed

### ISSUE THREAD

**Issue by centu81** [trivago/cluecumber-report-plugin#236]
Expected Result: undefined scenarios should be shown as skipped not failed.
Sample JSON:
`[
  {
    "description": "This is a description of undefined scenarion",
    "elements": [
      {
        "description": "hook is failing\nwhy?",
        "id": ";",
        "keyword": "Scenario",
        "line": 2,
        "name": "This is a undefined scenario",
        "steps": [
          {
            "keyword": "Given ",
            "line": 3,
            "match": {
              "location": "NativeConstructorAccessorImplFails.java:-2"
            },
            "name": "this step fails",
            "result": {
              "duration": 340604218,
              "status": "undefined"
            }
          }
        ],
        "type": "scenario"
      }
    ],
    "id": "",
    "keyword": "Feature",
    "line": 1,
    "name": "Feature 2 Undefined Scenario",
    "uri": "features/feature2.feature"
  }
]
`

**Comment by laxersaz** [comment]
Thanks for reporting, I will look into this.

**Comment by laxersaz** [comment]
ready for release.

**Comment by laxersaz** [comment]
Released as 2.3.4
