### ISSUE TITLE
How to show browser wise report in cluecumber?

### ISSUE THREAD

**Issue by kkch19** [trivago/cluecumber-report-plugin#237]
**My feature file:**

Feature: Login Page

  @Login
  Scenario: Verify Continue button visibility on Login page
    Given Start the application
    When Click on Sign In button
    Then Continue button visibility on Login page "true"

**My testng.xml file**

<suite name="TYS Automation Suite" parallel="tests" thread-count="1">

  <test name="Using Google Chrome" preserve-order="true">  
  <parameter name="Browser" value="Chrome"/>
    <classes>
      <class name="runner.TestRunner"/>
    </classes>
  </test> 
  
<test name="Using Firefox" preserve-order="true">  
  <parameter name="Browser" value="Firefox"/>
    <classes>
      <class name="runner.TestRunner"/>
    </classes>
  </test> 

**Testrunner file:**

@CucumberOptions(
		features = "src/test/java/features",
		glue = {"stepdefinition"},
		tags = {"@Login"},

**Plugin** 

<plugin>
<groupId>com.trivago.rta</groupId>
	<artifactId>cluecumber-report-plugin</artifactId>
		<version>2.3.1</version>
			<executions>
				<execution>
						<id>report</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>reporting</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<sourceJsonReportDirectory>${project.build.directory}\cucumber-report\</sourceJsonReportDirectory>
					<generatedHtmlReportDirectory>${project.build.directory}\generated-report\</generatedHtmlReportDirectory>
					<expandBeforeAfterHooks>true</expandBeforeAfterHooks>
					
				</configuration>
			</plugin> 

As per the above configuration:
- Test case starts running in chrome browser
- After end of chrome browser execution
- Test case starts execution in Firefox browser

After end of the firefox execution, report getting generated with Firefiox browser results.

My question is, I want to show both the browser reports in cluecumber report. 

How to do that.? Please guide me.

**Comment by laxersaz** [comment]
Are the test results written to two different json files or is the second Firefox test run simply overwriting the Chrome test run data?

**Comment by laxersaz** [comment]
Closed due to no reaction.
