### ISSUE TITLE
Reports not being generated when running from .jar file

### ISSUE THREAD

**Issue by pedrofg** [trivago/cluecumber-report-plugin#238]
Hi all, I have a cucumber project where I place my java classes under src/main instead of src/test and the reason for that is because I need to run this project as an executable jar (Jenkins builds this jar using maven). 
When I run it via 'java -jar' I am able to see the default reports from the Cucumber framework but not the ones from Cluecumber unless I specifically run the maven command  'mvn cluecumber-report:reporting' which I can't since I need to run via .jar file.
I can see that whenever I run via 'java -jar' I can see the json file created but not the report (html,css,js). Is there any way I can invoke this report to be created via Java later on?

Has anyone dealt with this before?

**Comment by laxersaz** [comment]
Why can't you run it via Maven if you use Maven to build it anyways? The generated JSON files are not contained inside the jar, are they? Cluecumber only needs the JSON files, nothing else.

**Comment by pedrofg** [comment]
Hi Benjamin, first thanks for asking my question. Those tests I am developing I will run against the system working in fact and not mocking, in the server, there is no maven nor internet connection so I use maven just to build the jar but not run the tests. 

The JSON files are generated in the file system and not inside the jar file, this is working now, I can see the default report with the html page. The cluecumber generates the JSON file since it is done by the plugin defined in the runner class I believe but it does not generate the report (html...) which I believe is done by the maven plugin. I just need to call the Cluecumber to finish the generation after all my tests are executed. If there is a programmatically way to trigger Cluecumber giving the JSON file would work as well. Any ideas?

**Comment by laxersaz** [comment]
Cucumber generates the json files via the runner class plugin. In order to use Cluecumber reports, it has to be invoked via Maven after the tests have run. So if your Jenkins has Maven support, call `mvn cluecumber-report:reporting` and pass the json location and output directory via the according system properties. If it does not have Maven support (which does not sound like it since Jenkins builds the jar anyways), you can also have a docker container with Maven run the reporting afterwards.

**Comment by laxersaz** [comment]
Closing this due to no further reaction.

**Comment by ThomasSun001** [comment]
I got the same question as @pedrofg has, well, I want to package an executable jar file, then it is potable which can run without jenkins and mvn at all, in a pc installed java, and I don't have maven and jenkins installed, then i run into this problem

**Comment by bischoffdev** [comment]
This is strictly a Maven tool so it is not possible to invoke it in another way.
