### ISSUE TITLE
Question : Do we have any support to save the HTML source of the page on fail?

### ISSUE THREAD

**Issue by gheeno** [trivago/cluecumber-report-plugin#242]
Scenario : 
I'd like to see the HTML source of the page where the failed test ran on.

**Comment by laxersaz** [comment]
Hello, this question is unrelated to Cluecumber.
Cluecumber shows everything that is being attached to scenarios in your test framework (and is thus included in the Cucumber JSON files). So if you attach the page's source, it will show up in the report.

**Comment by gheeno** [comment]
oh neat! thank you! I'll create a hook then. Thank you so much!

**Comment by gheeno** [comment]
@laxersaz  - would you happen to know the best way to embed the String in the report?

**Comment by laxersaz** [comment]
In a Cucumber hook you can embed custom data in a scenario.
In Java it would be something like:
```
scenario.embed(screenshot, "image/png", "My screenshot");
```

You can also embed text, html or pretty much whatever you want.
