### ISSUE TITLE
Is there an issue with maven 3.6.3? I can't seem to generate a report. 

### ISSUE THREAD

**Issue by rcooper85** [trivago/cluecumber-report-plugin#243]
I'm having an issue generating the html report. When I run `mvn clean verify`, I can only see the cucumber-report/cucumber.json file being generated. However, when I run the `mvn cluecumber-report:reporting` command separately, a report is generated successfully. 

Here is my pom.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>JavaCucumberTAF</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>5.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>5.5.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>5.5.0</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>5.5.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>3.5.3</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
        </dependency>
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.0.0-M4</version>
                </plugin>
                <plugin>
                    <groupId>com.trivago.rta</groupId>
                    <artifactId>cluecumber-report-plugin</artifactId>
                    <version>2.3.4</version>
                    <executions>
                        <execution>
                            <id>report</id>
                            <phase>post-integration-test</phase>
                            <goals>
                                <goal>reporting</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
                        <generatedHtmlReportDirectory>${project.build.directory}/generated-report</generatedHtmlReportDirectory>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>`

Here's a snippet of my project structure: 
![image](https://user-images.githubusercontent.com/20299737/78815793-a660c000-79c8-11ea-8c31-426796e7f2fd.png)

This is what is generated after running `mvn clean verify` : 
![image](https://user-images.githubusercontent.com/20299737/78815874-c6907f00-79c8-11ea-9261-5837412cb831.png)

**Comment by laxersaz** [comment]
You configured Cluecumber for the `post-integration-test` phase but you don't run your tests as integration tests (using failsafe) but unit tests (using surefire). So either call both Maven goals back to back or configure Cluecumber for a different phase.

**Comment by rcooper85** [comment]
I updated the pom settings for cluecumber as below:
```
                    <executions>
                        <execution>
                            <id>report</id>
                            <phase>test</phase>
                            <goals>
                                <goal>reporting</goal>
                            </goals>
                        </execution>
                    </executions>
```
I then executed the command `mvn clean verify` but it still does not automatically generate the report. What's the best way of generating the report using surefire?

**Comment by laxersaz** [comment]
Do you see Cluecumber starting?

**Comment by laxersaz** [comment]
I just noticed you put Cluecumber into `pluginManagement` and not in `plugins`. This should be why it doesn't work.

**Comment by laxersaz** [comment]
pluginManagement: is an element that is seen along side plugins. Plugin Management contains plugin elements in much the same way, except that rather than configuring plugin information for this particular project build, it is intended to configure project builds that inherit from this one. **However, this only configures plugins that are actually referenced within the plugins element in the children.**

**Comment by rcooper85** [comment]
Hi Benjamin, I just removed the <pluginManagement> tags altogether and it worked :) 
Thank you for your help.

**Comment by laxersaz** [comment]
Perfect :-)
