### ISSUE TITLE
Render new lines from `scenario.write(lines);`

### ISSUE THREAD

**Issue by mpkorstanje** [trivago/cluecumber-report-plugin#244]
When adding text to a report using `scenario.write(lines);` new line characters are not represented in the output. For example these lines:

```
GET: [redacted] 
> Accept: text/plain, application/json, text/html, */* 
> Content-Length: 0 
> [redacted] : [redacted] 
> X-B3-TraceId: 9f0d9fc63029170a 
> X-B3-SpanId: 9f0d9fc63029170a 
> X-B3-Sampled: 1 
> traceId: 9f0d9fc63029170a 
> spanId: 9f0d9fc63029170a 
> sampled: 1 
> [redacted]: 532733aa-1550-47bc-ae14-696f09e6b296
```
are rendered as:

![image](https://user-images.githubusercontent.com/6946919/79229550-80716a80-7e63-11ea-90e2-ac4473d95b10.png)

which isn't great to read. There might be some CSS needed to respect newlines.

**Comment by laxersaz** [comment]
Thanks for reporting this, @mpkorstanje . Adding this to the upcoming 2.4.0 release.
