### ISSUE TITLE
Reporter doesn't run after testing

### ISSUE THREAD

**Issue by GregJohnStewart** [trivago/cluecumber-report-plugin#251]
Hello,

I run my cucumber with a simple `mvn test`, but this does not trigger the reporting with cluecumber (using the plugin config found on the README). Is there a way to get it to run after the test command? I can run the reporter just fine with `mvn cluecumber-report:reporting`

**Comment by GregJohnStewart** [comment]
Found that using the `verify` command accomplishes the testing and cluecumber reporting.

**Comment by GregJohnStewart** [comment]
Sorry.. looks like when tests fail, the cluecumber isn't run automatically, even with `verify`. Any hints?

**Comment by laxersaz** [comment]
It depends on your Maven setup. If you run with `verify` which verifies your build based on the test results. It will fail when the tests fail. This means everything after it is not executed anymore.

So you can 

- set up your Maven configuration so that it ignores the failed tests (this will run everything but pass the build everytime) or
- invoke the reporting goal in a separate Maven command after running the tests or
- ignore the failing tests but let a Maven enforcer rule check your build as the final step (we do that here based on the failsafe result xml files)

**Comment by GregJohnStewart** [comment]
Thanks for the response! Would you mind pointing me to the example of the third option? It looks interesting, and I am not privy to the details of the enforcer plugin.

**Comment by laxersaz** [comment]
You can do something like this (we use it in production):

```
                <executions>
                    <execution>
                        <id>Pass or fail build</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <trupiRule implementation="com.somecompany.YourCustomRule">
                                    <testSummaryXmlReport>${maven.failsafe.test.report}</testSummaryXmlReport>
                                </trupiRule>
                            </rules>
                            <fail>true</fail>
                        </configuration>
                    </execution>
                </executions>
```

An enforcer rule can have any custom logic to pass or fail a build.

**Comment by laxersaz** [comment]
Closed due to no further activity.

**Comment by josepj** [comment]
For future reference, another option is to use the [Maven Failsafe Plugin](https://maven.apache.org/surefire/maven-failsafe-plugin/index.html).

> _The Failsafe Plugin is designed to run integration tests while the Surefire Plugin is designed to run unit tests. The name (failsafe) was chosen both because it is a synonym of surefire and because it implies that when it fails, it does so in a safe way._

> _The Failsafe Plugin is used during the integration-test and verify phases of the build lifecycle to execute the integration tests of an application. The Failsafe Plugin will not fail the build during the integration-test phase, thus enabling the post-integration-test phase to execute._

[Using Failsafe Plugin to execute Cucumber scenarios with JUnit](https://maven.apache.org/surefire/maven-failsafe-plugin/examples/cucumber.html)

**Comment by laxersaz** [comment]
`verify` includes integration tests which use Failsafe. So it is implicitly included.

**Comment by josepj** [comment]
@laxersaz, I had it in the back of my mind that I had seen the use of Maven Failsafe plugin somewhere and finally remembered where it was - [Running the generated tests with Maven failsafe](https://github.com/trivago/cucable-plugin#2-running-the-generated-tests-with-maven-failsafe) 😄 
Maybe I am missing something here, but once I designate the tests to run as integration tests using Failsafe, I see that all the tests are executed even if there are failures, the report gets generated and the build is marked as failed, without having to use the enforcer rule.

**Comment by laxersaz** [comment]
It depends on what you want to achieve. We need the enforcer rule since we have multiple test runs (including reruns) that generate multiple results. So we need a special rule to determine when a test fails in case some are rerun.
