### ISSUE TITLE
âœ½ symbol in exception stacktrace.

### ISSUE THREAD

**Issue by grasshopper7** [trivago/cluecumber-report-plugin#253]
**Describe the bug**
The 'âœ½' symbol is displayed in the stacktrace of the 'scenario-detail' page. This is on the line detailing the feature file location details. I am using the version 2.5.0, on windows.

**To Reproduce**
1. Run tests with a failing scenario.
2. Click on failing scenario to get details.

**Expected behavior**
The '?' or '✽' should be displayed. Seen the '?' in other reporting solutions but cucumber console displays '✽'. The later seems to be the correct, as per this - https://utf8-chartable.de/unicode-utf8-table.pl?start=9920&number=128&names=-&utf8=char. The relevant symbol is third from the bottom.

Maybe decoding the error_message byte array, by using the UTF_8 Charset could fix this.

**Attachments**
![symbol](https://user-images.githubusercontent.com/10829355/82562653-4cd8dd00-9b93-11ea-9435-a8d4025a92ad.png)
Cucumber JSON report : 
`result": {
              "error_message": "java.lang.AssertionError: error\r\n\tat stepdefs.Stepdefs.throwException (Stepdefs.java:48)\r\n\tat âœ½.Throw exception(classpath:stepdefs/experiment.feature:15)\r\n",`

**Additional context**

**Comment by laxersaz** [comment]
Thanks for reporting this - will look into it for the next release.

**Comment by laxersaz** [comment]
This is just taken from the json as is. So the error must be before the report generation which is out of Cluecumber's scope.
