### ISSUE TITLE
Cluecumber Report support for NodesJs

### ISSUE THREAD

**Issue by jaydeepqa** [trivago/cluecumber-report-plugin#255]
Can you please let us know if Cluecumber report support is there for NodeJs. If no can you please let us know if there is any plan for that?

**Comment by laxersaz** [comment]
Cluecumber is primarily a Maven plugin. The next iteration of the project will have more shapes. However, I don't have any plans to make a JS version of it.

**Comment by laxersaz** [comment]
You can of course still generate reports using Maven after running your JS based tests.
