### ISSUE TITLE
If I run same scenario multiple times but in different browser, there is no way to categorize/display scenario by browser or OS

### ISSUE THREAD

**Issue by motivatedmind** [trivago/cluecumber-report-plugin#256]
**Is your feature request related to a problem? Please describe.**
If I run same scenario multiple times but in different browser, there is no way to categorize/display scenario by browser or OS. 

**Describe the solution you'd like**
In my project I pass browser values from CLI and then use testNg data provider to iterate a scenario for each browser supplied. The problem is that, as the same scenario is run multiple times, this gives an impression that there are duplicate entries in the report [though there are not exactly, because there is a difference of browser but one doesn't know that]. Could there be a possibilty to supply a custom value to cluecucumber. This category is then applied for each scenario. So when the report is generated, at home page I can just click category and then it shows all scenarios that has this category defined. This way one can sort reports by their choice of criteria like browser/OS/author etc.

**Describe alternatives you've considered**
So far I couldn't find anything yet.

**Additional context**
I get one json per scenario run. In other words I get 2 jsons if I run same scenario for chrome & firefox.

![image](https://user-images.githubusercontent.com/53520137/85295838-1b1ea300-b4be-11ea-8a62-dc9c23e3b512.png)

**Comment by laxersaz** [comment]
As Cluecumber uses the Cucumber json files which don't contain this information, it is not really possible without hacks such as attaching custom values that Cluecumber can interpret. However, these values would also show up in other reports but as meaningless overhead.
We actually have completely separate reports per browser but this depends on how your test framework/pipelines run these tests.
