### ISSUE TITLE
Scenario does not show doc_string value in the report

### ISSUE THREAD

**Issue by aritranayak** [trivago/cluecumber-report-plugin#258]
**Describe the bug**
My scenario has a doc_string which does not get reflected in the generated report

**To Reproduce**
1. Create a Scenario step that has a doc_string like:
```
   When User sends the below post request:
    '''
    {"id": 1, "name": "Alex"}
    '''
```
2. Run the test
3. Generate the report
4. See the scenario in that report

**Expected behavior**
Expected to see the scenario step:
```
  When User sends the below post request:
    '''
    {"id": 1, "name": "Alex"}
    '''
```
But only seeing the below result:
```
  When User sends the below post request:
```

**Additional context**
Note, the generated JSON file does have the `doc_string` value correctly

**Comment by laxersaz** [comment]
There is a button in the top right corner of the report that shows the docstrings.
Also, if you want to always show them, you can set this reporting option:

```
<expandDocStrings>true</expandDocStrings>
```

This is described here:
https://github.com/trivago/cluecumber-report-plugin#auto-expand-certain-report-sections

**Comment by aritranayak** [comment]
Thanks @laxersaz . It works absolutely fine with both the approaches.
