### ISSUE TITLE
Test Trends Report

### ISSUE THREAD

**Issue by dhana-r** [trivago/cluecumber-report-plugin#259]
**Is your feature request related to a problem? Please describe.**
This plugin is very nice but there is no way to report the trends of test. 
 
**Describe the solution you'd like**
I feel it would be more beneficial if we have trends report similar cucumber-reports(jenkins)

**Describe alternatives you've considered**
maven-cucumber-reports plugin is alternative

**Comment by laxersaz** [comment]
Test trends are not included in Cucumber json files. So the only way to do this is to keep statistics within the plugin context. This is out of scope for Cluecumber as it is meant to be a tool to report a single test suite run.
