### ISSUE TITLE
Final screenshots/ embeds not shown in reports

### ISSUE THREAD

**Issue by GregJohnStewart** [trivago/cluecumber-report-plugin#261]
I'm experiencing an issue where items embedded in the scenario in a method annotated with `@After` don't appear in the cluecumber reports. I believe that they are correctly being embedded because they appear in the default Cucumber html output.

**Comment by laxersaz** [comment]
Have you checked that the after hooks are displayed in the report by clicking on the upper right button in the report?
You can also display after hooks per default using `<expandBeforeAfterHooks>true</expandBeforeAfterHooks>`

**Comment by laxersaz** [comment]
@GregJohnStewart did this solve it?

**Comment by GregJohnStewart** [comment]
Apologies, it has been busy. Yes, it did, Thanks!
