### ISSUE TITLE
srcdoc in iframe not escaped correctly

### ISSUE THREAD

**Issue by pgasior** [trivago/cluecumber-report-plugin#263]
**Describe the bug**
Content in srcdoc attribute of iframe needs additional escaping of `&` character. [HTML spec](https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-iframe-srcdoc).
For example `&lt;` needs to be escaped to `&amp;lt;`
This shows when trying to display HTML escaped content inside `<pre>`
Report has iframe with content unescaped. When I open the attachment HTML file directly, it is escaped.

**To Reproduce**
1. Add HTML attachment with `<pre>&lt;h1&gt;should be escapedd&lt;/h1&gt;</pre>`

**Expected behavior**
Escaped HTML tags remain escaped inside iframe in report

**Attachments**
JSFiddle with current behavior [link](https://jsfiddle.net/pz8056bf/)
JSFiddle with expected behavior [link](https://jsfiddle.net/nf8ksw6j/)

**Comment by laxersaz** [comment]
Thanks for reporting this!

**Comment by pgasior** [comment]
I think that this also applies to escaping `"` in `Embedding.decodeData(string)`. It shouldn't be converted to `'` but to `&quot;`. 
Citing the spec `And remember to escape ampersands before quotation marks, to ensure quotation marks become &quot; and not &amp;quot;`.

So if I understand this correctly fix would be in Embedding.java
```decodedData.replaceAll("&", "&amp;").replaceAll("\"", "&quot;");```

**Comment by laxersaz** [comment]
Will be fixed in 1.9.0 (release planned for today).

**Comment by gurshafriri** [comment]
👋 @laxersaz do you see this as a potential security issue? 
if it is, we (at [Snyk](https://snyk.io) would like to add it to our vulnerability database.

**Comment by laxersaz** [comment]
I don't quite follow your question. I am not an expert in software security.
