### ISSUE TITLE
Show (filtered) tags on the scenario summary page

### ISSUE THREAD

**Issue by codingHahn** [trivago/cluecumber-report-plugin#266]
**Is your feature request related to a problem? Please describe.**
I tag every scenario with its corresponding issue number (e.g. @issue_2342). I want to see this tag on the scenario summary page.

**Describe the solution you'd like**
A new column titled tags with an optional filter would be best. I only want to see the tags that start with "issue". This filter could be specified at compile time.

**Describe alternatives you've considered**
none

I already have the new column in my fork. How should the tag filter be implemented, considering that there is already a `tagFilter` in the code?

**Comment by laxersaz** [comment]
I intentionally wanted to keep the scenario summary as decluttered as possible. For tags, there is already the "all tags" page that enables searching and filtering for specific tags and going directly to scenarios with a specific tag.

**Comment by codingHahn** [comment]
Would you accept it if it would be implemented as a configuration parameter?

**Comment by laxersaz** [comment]
Even if this were available as a config parameter, the resulting view would look horrible when scenarios have multiple tags. This seems like an edge case that is specific to your requirement. Also, because there is already a tag specific page available with similar functionality, I would rather not accept it.

**Comment by codingHahn** [comment]
I understand. This is a niche use case. Another question: How do I make the example project use the local cluecumber for generating the report?

**Comment by laxersaz** [comment]
If you have a local version built, it should be in your local maven (`.m2`) directory. Once it is there and has the same or a newer version as the "official" version, it should be automatically used from there.

**Comment by codingHahn** [comment]
Thanks!
