### ISSUE TITLE
Doc String not show in report

### ISSUE THREAD

**Issue by panchitoboy** [trivago/cluecumber-report-plugin#267]
**Describe the bug**
I have an instruction with a String parameter and a doc string 

![image](https://user-images.githubusercontent.com/7557680/107738596-44b76380-6d07-11eb-8c19-266b54aad7c2.png)

But the doc string is never show in the report

![image](https://user-images.githubusercontent.com/7557680/107738682-76c8c580-6d07-11eb-9701-ff30e9216865.png)

**Expected behavior**

See the content of the doc string in the report

**Additional context**
Version 2.6.1

**Comment by laxersaz** [comment]
You have a button in the upper right corner of the scenario overview pages to display doc strings.
If you want to display them automatically, just use the `<expandDocStrings>true</expandDocStrings>` config setting.

**Comment by panchitoboy** [comment]
Hi, thanks for your answer..

Its the first time that i notice the buttons "show Scenario hooks" and "show DocStrings"

Thanks you :)
