### ISSUE TITLE
Parameter output from `customParameters`/ `customParametersFile` does not end up on page specified by `startPage`

### ISSUE THREAD

**Issue by GregJohnStewart** [trivago/cluecumber-report-plugin#269]
**Is your feature request related to a problem? Please describe.**
I would like to have my reports open to the "All Features" page, but the custom parameters I have defined only ever render on the "All Scenarios" page.

**Describe the solution you'd like**
I feel that the output of the custom parameters should render on the start page, not specifically only the "All Scenarios" page.

**Comment by laxersaz** [comment]
This is a good suggestion, will keep this in mind for the future. Feel free to add this in a PR, if you like.

**Comment by bischoffdev** [comment]
This is added in 2.8.0
