### ISSUE TITLE
More CSS selectors on page elements

### ISSUE THREAD

**Issue by GregJohnStewart** [trivago/cluecumber-report-plugin#270]
**Is your feature request related to a problem? Please describe.**
Being able to use CSS to tweak the page is an awesome tool, but not all elements have a specific enough CSS class to easily select and interact with them.

**Describe the solution you'd like**
Simply more specific CSS selectors for more page elements. Examples:

 - for each section at the top of many pages; "Scenario Results", "Suite Test Time", etc.
 - Embedded images (would love to specify a border for them), and other data. Perhaps a selector for each data type?
 - specific tables throughout the pages

**Comment by laxersaz** [comment]
Hello @GregJohnStewart ,

unfortunately, I don't have any time to work on Cluecumber at the moment. If you want to open a PR for this, I am happy to review it, though!

**Comment by GregJohnStewart** [comment]
Thanks! on it now. Tips on how best to test the changes locally?

**Comment by laxersaz** [comment]
You can do a `mvn clean install` which puts it into your local Maven repo. Then you can use it in your local project.

**Comment by GregJohnStewart** [comment]
Getting an error when building about no Mojo definitions being found, any ideas?

**Comment by laxersaz** [comment]
Maybe you have an old Maven version. 

Cluecumber requires Java >= 8 and Maven >= 3.3.9. It is available in Maven central.
(https://github.com/trivago/cluecumber-report-plugin#building)

**Comment by GregJohnStewart** [comment]
Got it working, and added a pull request for the changes

**Comment by GregJohnStewart** [comment]
Thanks! Curious how often you might put a release out, but I was going to try that other issue as well. Cheers!

**Comment by laxersaz** [comment]
I will wait with the next release until there is a little more in it.
