### ISSUE TITLE
cucumber junit- spark extent report not generating with mvn verify command

### ISSUE THREAD

**Issue by Manasr1** [trivago/cluecumber-report-plugin#272]
please help on this. i tried running the  mvn verify after running maven command i get BUILD SUCCESSFUL on the console.

But when i run testRunner class directly it generates the spark extent perfectly fine
I want to achieve the same through mvn verify.

I have attached the snapshot of POM.xml and the configuration of failsafe plugin.
![image](https://user-images.githubusercontent.com/31305121/115889518-a4ea2480-a471-11eb-830f-d0213b8737d2.png)
![image](https://user-images.githubusercontent.com/31305121/115890206-538e6500-a472-11eb-81cc-b85664a1d790.png)
directory structure
![image](https://user-images.githubusercontent.com/31305121/115890295-6d2fac80-a472-11eb-9a54-3fb4036c4ea7.png)

**Comment by laxersaz** [comment]
I don't think your question has anything to do with Cluecumber. This is not the Extent Report repository.
