### ISSUE TITLE
Combining the json files into single report when ran in multiple jenkin jobs

### ISSUE THREAD

**Issue by rahulbommanaboina** [trivago/cluecumber-report-plugin#274]
Hi Team ,

We have a scenario where we run multiple automation jobs in jenkins , since the report generation is inside the project , its creating individual report for each job , is there a way we can use the plugin which can combine all json files of different jobs in jenkins and create a report ? 
'If we have this plugin for jenkins then may we can use this pipeline stage and build the report , can you please suggest if this is possible.

**Comment by bischoffdev** [comment]
You don't have to have Cluecumber in the same project as the tests. It may well be a completely separate Maven invocation that can be used to combine the reports of multiple jobs into one.

**Comment by bischoffdev** [comment]
Closed due to no reaction.
