### ISSUE TITLE
How to generate HTML report from a JAR file without MAVEN ?

### ISSUE THREAD

**Issue by brizuelalionel** [trivago/cluecumber-report-plugin#275]
I would like to refer to this issue that was closed with no solution at the end :
https://github.com/trivago/cluecumber-report-plugin/issues/238

I also have the same issue as @pedrofg

How can I generate an HTML report using this plugin from a JAR file ?

I have to deliver a .jar file that runs Selenium tests and then generate an HTML report using this plugin. This .jar file could be executed using java -jar command anywhere on any machine where Maven is not installed on it.

Is there any way to achieve this using Java code , cucumber cli api, etc ?

**Comment by bischoffdev** [comment]
In its current stage, this is not possible as it is a Maven plugin. Thus, it requires Maven to run.
A solution is to use a standard Maven Docker container to run the reporting in.
