### ISSUE TITLE
Generate json report

### ISSUE THREAD

**Issue by pdkhanh** [trivago/cluecumber-report-plugin#276]
Hi there,

I'm using this plugin and was very interesting
I've a request that can we generate the merged json file from multiple json

I need this file to import to jira

Thanks

**Comment by bischoffdev** [comment]
Hello, as Cluecumber is not intended to be a Cucumber JSON merger but a reporting tool, I am afraid this is out of scope for your request.

**Comment by pdkhanh** [comment]
Thanks bischoffdev
