### ISSUE TITLE
Scenario Report - Bar Chart doesn't render correctly

### ISSUE THREAD

**Issue by gitissuepost** [trivago/cluecumber-report-plugin#278]
For each scenario, it renders a bar chart for overview of each step. However, the chart doesn't render a bar for each step.

Some links from the sample report:

[Link 1](http://cluecumber.softwaretester.blog/pages/scenario-detail/scenario_8.html)
[Link 2](http://cluecumber.softwaretester.blog/pages/scenario-detail/scenario_7.html)
[Link 1](http://cluecumber.softwaretester.blog/pages/scenario-detail/scenario_1.html)

Thanks

**Comment by bischoffdev** [comment]
It actually does. But the scale is one second, so you don't see the quick steps.

**Comment by gitissuepost** [comment]
Is there a way, we can set the configuration. So that the scale will get adjusted automatically based on the execution duration? That wauy, it will populate all the bars.

**Comment by bischoffdev** [comment]
Sure that would be a possibility. There is no way to set this from the outside at the moment but if you want to create a PR, feel free to do so. Otherwise, we can keep this in mind for a future release.

**Comment by bischoffdev** [comment]
Fixed in 2.9.0
