### ISSUE TITLE
Scenario Report marked as Passed even when a step is skipped

### ISSUE THREAD

**Issue by gitissuepost** [trivago/cluecumber-report-plugin#283]
**Describe the bug**
Scenario report says passed even when a step is tagged as skipped. This is reflecting in the sameple report as well.

[Sample Report](http://cluecumber.softwaretester.blog/pages/scenario-detail/scenario_6.html)

Currently, if all the steps are skipped, then only it is tagging as skipped

**Expected behavior**

Unless all the steps are passed, the report should not say the scenario is passed.
If there is a failure step, then it should be marked as failed
Otherwise if there is a skipped step, it should be moved to skipped.

**Comment by bischoffdev** [comment]
A scenario is considered skipped when all steps are skipped. When there are passing steps before it is considered passed. This is according to the official Cucumber guidelines.
