### ISSUE TITLE
Failed to collect dependencies at com.trivago.rta:cluecumber-report-plugin:jar:0.2.0

### ISSUE THREAD

**Issue by jdoriyastpl** [trivago/cluecumber-report-plugin#30]
### Expected behavior
At local system report is generating
### Actual behavior
Not able to generate report on docker
### Reproduction steps
mvn clean install verify -Pparallel
### Additional details (Maven version, Java version, etc.)
Execution report of goal com.trivago.rta:cluecumber-report-plugin:0.2.0:reporting failed: Plugin com.trivago.rta:cluecumber-report-plugin:0.2.0 or one of its dependencies could not be resolved: Failed to collect dependencies at com.trivago.rta:cluecumber-report-plugin:jar:0.2.0 -> com.google.code.gson:gson:jar:2.8.2: Failed to read artifact descriptor for com.google.code.gson:gson:jar:2.8.2: Could not transfer artifact com.google.code.gson:gson:pom:2.8.2 from/to central (https://repo.maven.apache.org/maven2): Connection reset

**Comment by laxersaz** [comment]
Hi, I don't think this is a Cluecumber issue. It rather looks like a connection issue between your container and Maven Central.

**Comment by jdoriyastpl** [comment]
@laxersaz  Thanks for response,
I have tried to execute 2 features and plugin worked well, But as I increased the feature files count then connection reset between container and maven as you said. any resolution for this?

**Comment by laxersaz** [comment]
Hi! Maybe Maven does not have enough resources allocated for a higher number of features. You could try giving it more with `-Xms256m -Xmx1024m`
