### ISSUE TITLE
Encoding issues with Norwegian based Cucumber features

### ISSUE THREAD

**Issue by alenmeister** [trivago/cluecumber-report-plugin#32]
### Expected behavior
Was not expecting there to be any major issues related to encoding with non-english special characters (ie, æøå).

### Actual behavior
Looks like the headers for the feature and scenario columns are not being rendered correctly.
None of the steps from the detailed page are affected by this.

I attached a screendump of the the headers from the overview page. 

### Reproduction steps
1. Make sure language in feature file is set to "no":
```# language: no```
2. Use any of the following special characters in the "Feature" and/or "Scenario" section:
```
Egenskap: Søknadsskjema
  Scenario: En sluttbruker skal kunne fylle ut søknadsskjemaet og søke om foo
```

### Additional details (Maven version, Java version, etc.)
Java version: 1.8.0_152
Apache Maven 3.5.2
Cluecumber 0.2.0

![encoding_issues](https://user-images.githubusercontent.com/1524302/36636390-64bd13d8-19c6-11e8-8474-067e14f3ccdb.PNG)

**Comment by laxersaz** [comment]
Hi @alenmeister ! Thanks for reporting this. I will look into it asap.

**Comment by laxersaz** [comment]
Also created related Cucable issue https://github.com/trivago/cucable-plugin/issues/50

**Comment by laxersaz** [comment]
I fixed the Cucable issue first to support non-english languages in my whole Cucumber tool chain:
https://github.com/trivago/cucable-plugin/issues/50

Next step is fixing it in the Cluecumber Report plugin.

**Comment by alenmeister** [comment]
Great news! This will make my project lead quite happy.

**Comment by laxersaz** [comment]
Hello @alenmeister !

I tried it with different languages and could not reproduce the encoding issue at all.

<img width="860" alt="screen shot 2018-03-08 at 22 00 36" src="https://user-images.githubusercontent.com/5775857/37176292-3ef863a0-231c-11e8-8976-b098376ae69a.png">

Did you make sure your feature files are UTF-8 encoded?
And did you set the encoding in your POM file?

```
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>
```

If this problem still persists, could you share a little more detail about the platform and setup you are using?

**Comment by alenmeister** [comment]
Yes, sir!

My feature files should be UTF-8 encoded and the correct properties are defined in my POM file as well.
One thing to take note of is that I'm for the most part using Scenario Outline in my feature files. Not sure if that matters at all.

Other than that, I'm using IntelliJ 2017.3.4 (Community Edition), build #IC-173.4548.28 on Windows 10 version 1703, build 15063.909. Something else you'd like to know?

**Comment by laxersaz** [comment]
I will investigate this further. Very strange since the headers look fine for me too:

<img width="725" alt="screen shot 2018-03-09 at 11 14 00" src="https://user-images.githubusercontent.com/5775857/37202571-210cc060-238b-11e8-995b-fa3ef92c56e7.png">

**Comment by laxersaz** [comment]
Which browser are you using to look at the reports?

**Comment by alenmeister** [comment]
Using Chrome Version 64.0.3282.140 (Official Build) (32-bit)

**Comment by alenmeister** [comment]
Hey, @laxersaz!

I'll give it another go with only one scenario defined in the feature file. I'll also check to see if a colleague of mine has the same problem. If the issue still persists, I'll create a repo with an example for you clone and run. Sounds like an okay plan?

**Comment by laxersaz** [comment]
Great plan! I was not able to reproduce the problem yet.

**Comment by alenmeister** [comment]
My colleague and I are still getting the same encoding issues. I've stripped away a lot of the code we're using to the bare minimum, and created a private repo for you to clone. I'm sending you an invite as we speak.

**Comment by laxersaz** [comment]
This is very strange, I tested your project and I don't see this issue. Actually, this screenshot shows the generated report in Safari, Firefox and Opera (works also in Chrome).

![screen shot 2018-03-20 at 15 55 42](https://user-images.githubusercontent.com/5775857/37662538-92780ff0-2c57-11e8-9fec-09cb4147a7fc.png)

I also attached the generated report directory as a zip files so we can see if the same report looks different on your system.

[reports.zip](https://github.com/trivago/cluecumber-report-plugin/files/1829868/reports.zip)

Anyways, I am positive we can solve this mystery :-)

**Comment by alenmeister** [comment]
That is indeed very strange. Here's a screen dump of my report:
![reports](https://user-images.githubusercontent.com/1524302/37670981-f4c7831c-2c6a-11e8-83f7-98ea772ce64e.PNG) 

Could there be something with the settings I have set in IntelliJ?
![intellij_file_encodings](https://user-images.githubusercontent.com/1524302/37670983-f8194c1c-2c6a-11e8-877d-c2564e190923.PNG)

**Comment by laxersaz** [comment]
Did you check my attached report zip file and how it looks on your system?

**Comment by alenmeister** [comment]
Yes, they look as they should look. No weird characters at all. What gives?

**Comment by laxersaz** [comment]
I have the same settings in IntelliJ. If my reports look fine, that definitely looks like a setting on your system. Do the generated feature files that Cucable generates look correct? Or is the encoding issue there as well?

**Comment by alenmeister** [comment]
No encoding issues with the generated reports from Cucumber. Also, I have no issues with the maven-cucumber-reporting plugin from masterthought. I noticed you are using macOS, did you try running my repo on a Windows machine?

**Comment by laxersaz** [comment]
I don't have a windows machine here. However, I have an idea of what the reason could be. I will add more explicit UTF-8 encoding in the next 0.6.0 release. I'll keep you posted.

**Comment by laxersaz** [comment]
Hello @alenmeister !
Could you please try this jar and see if it would fix your problem?
Thanks,
Benjamin

[cluecumber-report-plugin-0.6.0.jar.zip](https://github.com/trivago/cluecumber-report-plugin/files/1883004/cluecumber-report-plugin-0.6.0.jar.zip)

**Comment by alenmeister** [comment]
The JAR failed to build. Take a look:
https://pastebin.com/xgW7Nsi9

**Comment by laxersaz** [comment]
Alright I will check

**Comment by laxersaz** [comment]
[cluecumber-report-plugin-0.6.0.jar.zip](https://github.com/trivago/cluecumber-report-plugin/files/1894957/cluecumber-report-plugin-0.6.0.jar.zip)

Please try this one.

**Comment by alenmeister** [comment]
Still failing, now with a different error:
https://pastebin.com/4MLR75CR

First time I installed it manually using `mvn install:install-file`
Second time I included the maven-install-plugin to my pom.xml, as such:
https://pastebin.com/Sar5Wryp

Am I doing it wrong?

**Comment by laxersaz** [comment]
OK, let's start over 🥇
I will release a snapshot version that you can try soon. This thing needs to be fixed 🤒

**Comment by laxersaz** [comment]
@alenmeister I just released v0.6.0 which should be available in maven central soon. Please try this one 👍 
Also I added an example project in this repo.

**Comment by alenmeister** [comment]
Hey, @laxersaz! I changed the version of cluecumber in my POM file on several of my projects, and they all seem to get the exact same error as previously mentioned. I'm attempting one last try when I come home on a fresh project outside of our internal network at the office. I'll let you know by tonight.

**Comment by laxersaz** [comment]
@alenmeister , anything new?

**Comment by alenmeister** [comment]
@laxersaz I promise to an update to you within this weekend. Been on holidays, without a laptop. Should’ve done it before I left, my apologies!

**Comment by alenmeister** [comment]
![cluecumber_report](https://user-images.githubusercontent.com/1524302/39943862-b511884e-5564-11e8-9c78-7f53df2ccc38.PNG)

Would you look at that! Thanks for putting the time in. I owe you a beer!

**Comment by laxersaz** [comment]
Hurray! Alright let's meet 😁
