### ISSUE TITLE
Background steps display in reverse order

### ISSUE THREAD

**Issue by rcmedina** [trivago/cluecumber-report-plugin#33]
### Expected behavior
Background steps should display in order they are given

### Actual behavior
Background steps display in reverse order in report

### Reproduction steps
1. Create and run a feature file that uses Background steps.
2. Open Cluecumber report

### Additional details (Maven version, Java version, etc.)
Cluecumber version 0.3.0
![screen shot 2018-03-07 at 8 40 53 am](https://user-images.githubusercontent.com/37146992/37095618-6c96b08e-21e4-11e8-94d2-d4dff30fe1fb.png)

![screen shot 2018-03-07 at 8 32 21 am](https://user-images.githubusercontent.com/37146992/37095123-07e321f0-21e3-11e8-9cac-bca7b46fbce9.png)

**Comment by laxersaz** [comment]
Hello @rcmedina ,
thanks for the detailed report. A fix will be included in the next release.

**Comment by dgt-amexio** [comment]
As far as I am concerned, I am facing the same "mismatch" in steps order in Given/When/Then steps.
Will the fix cover all use cases or shall I create a separate issue ?

Kind regards
DGT

**Comment by laxersaz** [comment]
Does this only happen when using background steps? Then it will be covered here. If your issue happens without a background scenario, please create a new issue including reproduction steps.

Best,
Benjamin

**Comment by laxersaz** [comment]
This is fixed and will be released in v0.5.0

**Comment by dgt-amexio** [comment]
@laxersaz you're right, I was using background steps in my scenario.
Thx !
