### ISSUE TITLE
Feature based report

### ISSUE THREAD

**Issue by dgt-amexio** [trivago/cluecumber-report-plugin#37]
### Expected behavior
_not sure to post my feature request in the right way, feel free to redirect me to the right medium if available_

Do you have any plan to include a feature report on the overview page + feature result drilldown in order to browe results on a feature (or feature + subfeature) basis ?

### Actual behavior
No feature based report

### Reproduction steps
Not applicable : no feature based report yet

### Additional details (Maven version, Java version, etc.)
Not applicable : no feature based report yet

**Comment by laxersaz** [comment]
Thanks for reporting! It is alright how you created the feature request, don't worry :-)
