### ISSUE TITLE
Proposed feature : allow report look & feel customization through CSS

### ISSUE THREAD

**Issue by dgt-amexio** [trivago/cluecumber-report-plugin#38]
### Expected behavior
Introduce additional configuration in Cluecumber report plugin in order to let plugin users change report UI (example : change default background colors, introduce additional header icon, ...)

### Actual behavior
Cluecumber report UI cannot be customized "on the fly", unless by overriding HTML / CSS output once processed

### Reproduction steps
Not applicable : feature not yet available

### Additional details (Maven version, Java version, etc.)
Not applicable : feature not yet available

**Comment by dgt-amexio** [comment]
Currently I implemented a workaround consisting in 

- Creating a custom css stylesheet containing my custom rules for UI
- Making a private copy of the official cluecumber.css stylesheet + adding a @import directive pointing to my custom css stylesheet
- Taking advantage of the "maven-resources-plugin" as a report post-processor to include my custom css rules

Suggested approach might consist in 
- Defining a default empty "custom.css" stylesheet in Cluecumber Report Plugin
- Referencing this default stylesheet in HTML output files
- [Optionally] introduce an additional configuration parameter in Cluecumber Report Plugin to reference custom stylesheet + images location


This would make reporting customization easier by avoiding : 
- private copy of cluecumber.css (whose content might change on any new version)
- additional maven steps used as post-processors

**Comment by laxersaz** [comment]
Hello @dgt-amexio 

This is definitely planned. However, there are some bugs and features with a higher priority so it will  take some time to implement that.

Best,
Benjamin

**Comment by laxersaz** [comment]
Ready for release in 1.3.0
