### ISSUE TITLE
Documented configuration example is incorrect

### ISSUE THREAD

**Issue by qualityhabit** [trivago/cluecumber-report-plugin#40]
Integrated to my cucumber project following steps described in https://github.com/trivago/cluecumber-report-plugin/blob/master/README.md

### Expected behavior
A sample report should be created at  ${project.build.directory}/generated-report

### Actual behavior
Exception generated: org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.trivago.rta:cluecumber-report-plugin:0.3.0:reporting (default-cli) on project UniteBPCAutomation: The parameters 'generatedHtmlReportDirectory', 'sourceJsonReportDirectory' for goal com.trivago.rta:cluecumber-report-plugin:0.3.0:reporting are missing or invalid

### Reproduction steps
As described in README.md

### Additional details (Maven version, Java version, etc.)
I moved the configuration block in pom.xml as follows to fix:
```
<plugin>
    <groupId>com.trivago.rta</groupId>
    <artifactId>cluecumber-report-plugin</artifactId>
    <version>Check the version number above</version>
    <configuration>
           <sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
            <generatedHtmlReportDirectory>${project.build.directory}/generated-report</generatedHtmlReportDirectory>
    </configuration>
    <executions>
        <execution>
            <id>report</id>
            <phase>post-integration-test</phase>
            <goals>
                <goal>reporting</goal>
            </goals>
        </execution>
    </executions>
</plugin>

```

**Comment by laxersaz** [comment]
Thanks @qualityhabit !
I changed it in the documentation. In the next Cluecumber version there will be a full example project inside this repository.
