### ISSUE TITLE
scenario.write() output doesn't appear in the Before and After sections

### ISSUE THREAD

**Issue by rvarum** [trivago/cluecumber-report-plugin#48]
### Expected behavior
render cucumber Scenario.write() output to @Before and @After sections as well

### Actual behavior
current it's not rendered there, not sure if a bug :) or its an improvement.

### Reproduction steps
run some test with scenario.write() in the @Before and @After methods and generate report

### Additional details (Maven version, Java version, etc.)
maven 3.5.2
java 1.8

**Comment by laxersaz** [comment]
Thanks @rvarum I will add that.

**Comment by laxersaz** [comment]
Started developing for release 0.8.0...

**Comment by laxersaz** [comment]
This is done and will be released in 0.8.0
