### ISSUE TITLE
Html report does not get created when there are failures in the code

### ISSUE THREAD

**Issue by MMeholli** [trivago/cluecumber-report-plugin#49]
### Expected behavior
Report file should be created when tests failed
### Actual behavior
Report file only gets created when the tests pass
### Reproduction steps
through the terminal running mvn clean verify test
### Additional details (Maven version, Java version, etc.)
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
Java 1.8
<plugin>
                <groupId>com.trivago.rta</groupId>
                <artifactId>cluecumber-report-plugin</artifactId>
                <version>0.7.1</version>
                <executions>
                    <execution>
                        <id>test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>reporting</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceJsonReportDirectory>cucumber-html-reports</sourceJsonReportDirectory>
                    <generatedHtmlReportDirectory>generated-report</generatedHtmlReportDirectory>
                </configuration>
            </plugin>
```

**Comment by laxersaz** [comment]
This is the standard Maven lifecycle and not a Cucable issue. If a goal fails, the subsequent ones won‘t be executed. 
So you have basically two choices here:

- split the test and reporting phase into two separate maven calls or
- let surefire/failsafe ignore failed tests so the reporting phase gets executed.

**Comment by GregJohnStewart** [comment]
Would it be possible to get an example of the second option in the previous comment?

This feels like a fairly heavily asked for behavior

**Comment by mergimmeholli** [comment]
> Would it be possible to get an example of the second option in the previous comment?
> 
> This feels like a fairly heavily asked for behavior

@GregJohnStewart The options for this are whenever you run it through terminal/ci you can use the `-Dmaven.test.failure.ignore=true`.

Or you can do the same thing by adding `<testFailureIgnore>true</testFailureIgnore>` to the `<configuration>` of surefire in your pom.xml: 

```
 <plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <configuration>
     <testFailureIgnore>true</testFailureIgnore>
   </configuration>
 </plugin>
```

**Comment by MMeholli** [comment]
> Would it be possible to get an example of the second option in the previous comment?
> 
> This feels like a fairly heavily asked for behavior

@GregJohnStewart The options for this are whenever you run it through terminal/ci you can use the `-Dmaven.test.failure.ignore=true`.

Or you can do the same thing by adding `<testFailureIgnore>true</testFailureIgnore>` to the `<configuration>` of surefire in your pom.xml: 

```
 <plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <configuration>
     <testFailureIgnore>true</testFailureIgnore>
   </configuration>
 </plugin>
```

**Comment by GregJohnStewart** [comment]
Thanks for the example config, is quite helpful, but is it possible to also fail the build?

Asking as the maven build pass/fail is used in pipelines to determine if tests passed

**Comment by bischoffdev** [comment]
You can solve this by splitting the Maven calls into two separate ones, e.g. within a shell script.
1. Execute the tests and store the return value
2. Generate the report
3. Pass or fail the build using the stored return value from step 1

Alternatively you can use a Maven enforcer rule as the last step of your build that looks at the surefire or failsave result xml and passes of fails the build based on this info.
