### ISSUE TITLE
Also filter tables when filtering charts

### ISSUE THREAD

**Issue by high4life** [trivago/cluecumber-report-plugin#51]
### Expected behavior
Would it be possible to also filter tables when filtering a chart by type (passed, failed, skipped)?
For example in the Suite Overview when we click on the "passed" type to not display it into the chart, it could be cool to also filter the tables and to display only the "failed" and "skipped" scenarios (so it will be consistent with the Test Suite Result Chart).

Could be the same expected behavior for the Scenario details page to display only the step failure in one click and also useful in the Tag Summary page for reporting.

### Actual behavior
We can filter a chart by type  but the result in the tables are not filtered.

### Reproduction steps
N/A: new feature request
### Additional details (Maven version, Java version, etc.)
N/A

**Comment by laxersaz** [comment]
Hello @high4life! 
Thanks for your suggestion, this sounds like a great idea. I will certainly evaluate if this can be achieved!

**Comment by high4life** [comment]
Hello @laxersaz,

Thanks to you for this great cucumber reporting plugin !

**Comment by laxersaz** [comment]
Development in progress...

**Comment by laxersaz** [comment]
Example for new step graph:

```
        var chart = new Chart(ctx, eval({
            "data": {
                "labels": ["1", "2", "3", "4", "5", "6"],
                "datasets": [{
                    "data": [340.0, 0, 0, 440.0, 340.0, 0],
                    "backgroundColor": "rgba(240,0,0,1.000)",
                    "label": "failed",
                    "stack": "complete"
                }, {
                    "data": [0, 340.0, 440.0, 0, 0, 340.0],
                    "backgroundColor": "rgba(0,240,0,1.000)",
                    "label": "passed",
                    "stack": "complete"
                },]
            },
            "options": {
                "scales": {
                    "yAxes": [{
                        "ticks": {
                            "min": 0,
                        },
                        "stacked": true
                    }]
                }
            },
            "type": "bar"
        }));
```

**Comment by high4life** [comment]
Nice, I look forward to use this new "fancy" feature xD

**Comment by laxersaz** [comment]
Ready to release.

**Comment by laxersaz** [comment]
@high4life version 1.1.0 was just released and should be on Maven Central soon!
