### ISSUE TITLE
Include cluecumber to surefire report

### ISSUE THREAD

**Issue by nmash1937** [trivago/cluecumber-report-plugin#55]
I'm not sure if this is a cluecumber issue, but is there a way to provide documentation to add cluecumber to surefire reports.

**Comment by laxersaz** [comment]
Hello @nmash1937 , 
I am not sure I understand your request. Surefire can be the executer of Cucumber tests and Surefire's reports are different from Cucumber reports. So I would need some more information about what and how you are running your tests and what your desired report should look like.

**Comment by laxersaz** [comment]
Closing it for now. @nmash1937 , feel free to comment on it - when you do I will reopen it.

**Comment by japzio** [comment]
newbie here, wondering if cluecumber report plugin can be triggered by surefire?
