### ISSUE TITLE
not able to see charts in scenarios in report

### ISSUE THREAD

**Issue by SumanpreetJhinjer** [trivago/cluecumber-report-plugin#57]
charts are displaying well in features and tags but not in scenarios.
![scenariosissue](https://user-images.githubusercontent.com/40511096/42070709-615b2192-7b75-11e8-863f-a9377aaac344.png)

**Comment by laxersaz** [comment]
Hello,

please attach a json result file for me to test it. Alternatively yiu can also attach a zip file containing the generated report.

Best, 
Benjamin

**Comment by laxersaz** [comment]
Thanks a lot, I will investigate this further.

**Comment by laxersaz** [comment]
For me it looks correct.

![screen shot 2018-06-29 at 10 00 56](https://user-images.githubusercontent.com/5775857/42080557-665eb402-7b83-11e8-9ecf-04784709e478.png)

Which version of Cluecumber are you using? And which Browser are you using to view the report?

**Comment by SumanpreetJhinjer** [comment]
It's working fine with chrome editor but not with default eclipse editor.
cluecumber version 1.0.0

**Comment by laxersaz** [comment]
Hello @SumanpreetJhinjer ,
I don't know the Eclipse browser at all (I don't use Eclipse anymore). Also, the generated reports are designed for more common web browsers. If you have any JS errors that you can send me I can look into this issue further.

**Comment by SumanpreetJhinjer** [comment]
It's not throwing any error though...Thanks @laxersaz ....

**Comment by laxersaz** [comment]
I am rewriting the chart handling so it might be fixed in 1.1.0
