### ISSUE TITLE
Mismatching numbers on features report page

### ISSUE THREAD

**Issue by SumanpreetJhinjer** [trivago/cluecumber-report-plugin#58]
Hi Lax,

There is a bug on counting the number of features passed, Instead of number of features passed its stating the total number of runtime features passed which is basically the total number of scenarios.
PFA the screenshot.
![bug](https://user-images.githubusercontent.com/40511096/42077919-2abfc67e-7b98-11e8-8b32-c8388215395b.png)

**Comment by laxersaz** [comment]
This is intended. The passed, failed and skipped values refer to the scenarios since a feature does not really have one defined state. How would you handle features with a mix of passed, failed and skipped scenarios?

**Comment by laxersaz** [comment]
I added better labels to the numbers in 1.1.0
