### ISSUE TITLE
Malformed regular expression: Illegal/unsupported escape sequence

### ISSUE THREAD

**Issue by high4life** [trivago/cluecumber-report-plugin#59]
**Describe the bug**
Hello,

I have a step in which I pass an interval as a parameter in some examples:

Then the order list should contain 1 order on "<var1>" with a weight in interval <var2>
    Examples:
      | var1  | var2      |
      | str1   | !]0,100[ |
      | str2   | ]0,100[  |
[....]

All tests pass but when the cluecumber-plugin begins to parse the cucumber.json, I get this error:

build	28-Jun-2018 19:27:44	[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.0.0:reporting (report) on project pamfolio-testing-swing: Could not render page content: Malformed regular expression: Illegal/unsupported escape sequence near index 11
build	28-Jun-2018 19:27:44	[ERROR] \b!]0,100[\b
build	28-Jun-2018 19:27:44	[ERROR] ^
build	28-Jun-2018 19:27:44	[ERROR] 
build	28-Jun-2018 19:27:44	[ERROR] ----
build	28-Jun-2018 19:27:44	[ERROR] FTL stack trace ("~" means nesting-related):
build	28-Jun-2018 19:27:44	[ERROR] - Failed at: #assign stepName = stepName?replace("...  [in template "scenario-detail.ftl" at line 68, column 37]
build	28-Jun-2018 19:27:44	[ERROR] ~ Reached through: #nested  [in template "macros/page.ftl" in macro "card" at line 38, column 17]
build	28-Jun-2018 19:27:44	[ERROR] ~ Reached through: @page.card width="12" title="${elemen...  [in template "scenario-detail.ftl" at line 30, column 5]
build	28-Jun-2018 19:27:44	[ERROR] ~ Reached through: #nested  [in template "macros/page.ftl" in macro "page" at line 19, column 13]
build	28-Jun-2018 19:27:44	[ERROR] ~ Reached through: @page.page base="../.." links=["featu...  [in template "scenario-detail.ftl" at line 5, column 1]

I think this is a regression of cluecumber-plugin:1.0.0 because I had this report well built in 0.8.0.

**To Reproduce**
1. Try to reproduce this error by making a scenario with this kind of sentence and parameters:
Scenario Outline: Order list weights
[...]
Then the order list should contain 1 order on "<var1>" with a weight in interval <var2>
    Examples:
      | var1  | var2      |
      | str1   | !]0,100[ |
      | str2   | ]0,100[  |
[...]

**Expected behavior**
The result parser should not fail even if we pass such parameters with special characters like: !, [, etc....

**Attachments**
A part of the cucumber.json:

 "result": {
              "duration": 11685860341,
              "status": "passed"
            },
            "line": 13,
            "name": "the order list should contain 1 order on \"pf1\" with a weight in interval !]0,100[",
            "match": {
              "arguments": [
                {
                  "val": "1",
                  "offset": 30
                },
                {
                  "val": "pf1",
                  "offset": 42
                },
                {
                  "val": "!]0,100[",
                  "offset": 78
                }
              ],
              "location": "CommonOrderSteps.orderListShouldContain(String,String,String)"
            },
            "keyword": "Then "
          },

**Additional context**
N/A

**Comment by high4life** [comment]
Hi @laxersaz,
Many thanks !
Cheers,
Tomas

**Comment by laxersaz** [comment]
Your example is invalid JSON at 
`"name": "the order list should contain 1 order on "pf1" with a weight in interval !]0,100[",` because of the double quotes around `pf1`. If I use single quotes I get the same error message as you. So your bug is definitely valid.

**Comment by high4life** [comment]
Ok, I told myself the same thing ;)
Do you have any plan for the 1.1.0 release? Just to know if I should rollback the version or if  I can let my build as a "failure" for some days, knowing that it is only the extended report that fails.

**Comment by laxersaz** [comment]
I will most likely remove this feature in the next release and think about reimplementing it again. The thing is that the way it is done now, it will fail on certain regex characters. To implement it correctly, I would have to rely on the Cucumber argument offsets in the JSON file. These are apparently flawed on special characters.
Until then, I would recommend rolling back to the previous version until I release 1.1.0

**Comment by laxersaz** [comment]
I am planning on releasing 1.1.0 asap. It will take some more time though because I have to rewrite the chart handling since the charting library I use at the moment does not support the advanced features I need :-(

**Comment by laxersaz** [comment]
Oh maybe it works after all. I may have just found a way to do it:

![screen shot 2018-06-29 at 16 18 24](https://user-images.githubusercontent.com/5775857/42097320-2983b87c-7bb8-11e8-8786-39a98114eab4.png)

**Comment by high4life** [comment]
Oh yeah, great ! I'll follow your advise and rollback to 0.8.0 to wait for 1.1.0. Cool having a way to keep highlighting in 1.1.0 :)

**Comment by laxersaz** [comment]
Ready to release.
