### ISSUE TITLE
Could not render page content

### ISSUE THREAD

**Issue by high4life** [trivago/cluecumber-report-plugin#62]
**Describe the bug**
Hello,

After updating to the 1.1.0, I have this error on one of my scenarios:

build	04-Jul-2018 17:42:43	[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.1.0:reporting (report) on project pamfolio-testing-swing: Could not render page content: An error has occurred when reading existing sub-variable "nameWithArguments"; see cause exception! The type of the containing value was: extended_hash+string (com.trivago.rta.json.pojo.Step wrapped into f.e.b.StringModel)
build	04-Jul-2018 17:42:43	[ERROR] 
build	04-Jul-2018 17:42:43	[ERROR] ----
build	04-Jul-2018 17:42:43	[ERROR] FTL stack trace ("~" means nesting-related):
build	04-Jul-2018 17:42:43	[ERROR] - Failed at: #assign stepName = step.nameWithArgum...  [in template "scenario-detail.ftl" at line 67, column 33]
build	04-Jul-2018 17:42:43	[ERROR] ~ Reached through: #nested  [in template "macros/page.ftl" in macro "card" at line 38, column 17]
build	04-Jul-2018 17:42:43	[ERROR] ~ Reached through: @page.card width="12" title="${elemen...  [in template "scenario-detail.ftl" at line 31, column 5]
build	04-Jul-2018 17:42:43	[ERROR] ~ Reached through: #nested  [in template "macros/page.ftl" in macro "page" at line 19, column 13]
build	04-Jul-2018 17:42:43	[ERROR] ~ Reached through: @page.page base="../.." links=["featu...  [in template "scenario-detail.ftl" at line 5, column 1]
build	04-Jul-2018 17:42:43	[ERROR] ----

**To Reproduce**
I don't really know how to reproduce this bug because it failed after executing a lot of scenarios and I don't know which one has caused the failure...

**Expected behavior**

**Attachments**
Unfortunately I cannot send you my target of this build because of security policies.

**Additional context**

**Comment by laxersaz** [comment]
Trying to reproduce it but so far no luck. I tried it with removing arguments, removing the step name altogether, just trying to break the report generation. 

Could you run the report generation with the Maven `-X` flag and post the stack trace here?

**Comment by BillMatthews** [comment]
I have a similar stack trace but it may be a different cause - possibly related to use of characters such as '{' in scenario details. I can attach some of the stack trace if you want or create a new issue

**Comment by laxersaz** [comment]
Hi there, if you open a separate issue that would be great. If they are related I will link them.

**Comment by laxersaz** [comment]
I was able to reproduce this issue so I am now working on it.

**Comment by laxersaz** [comment]
I just release v1.1.1 with a fix for this issue. Please try this when it reaches Maven central and let me know :-)

**Comment by laxersaz** [comment]
Hello @high4life and @BillMatthews,

did the new version fix the rendering issue?

All the best,
Benjamin

**Comment by BillMatthews** [comment]
Yes, v1.1.1 seems to have resolved the issue I was having

Thanks for the quick turn around

**Comment by laxersaz** [comment]
Thanks for your feedback!

**Comment by tomaugs** [comment]
Hi @laxersaz ,

I was in holidays last week but I can now confirm that the new v1.1.1 has resolved the issue.
Thx a lot for this quick fix !

Thomas
