### ISSUE TITLE
Display the error message of a @AfterStep hook's failure

### ISSUE THREAD

**Issue by tomaugs** [trivago/cluecumber-report-plugin#65]
**Is your feature request related to a problem? Please describe.**
It might be possible to have failures in an @AfterStep hooks (available since cucumber v3) and this failure may happened after the last step of the scenario/feature. 
In this case everything is green (feature, scenario, steps) and no error message is displayed in the cluecumber report. But if you have a look on the basic cucumber html reports, the error message is displayed in red.

**Describe the solution you'd like**
It would be nice to fail feature + scenario summaries in this case and to write the error message in the scenario details view (like the cucumber html reports).

**Describe alternatives you've considered**
This is already done for @Before/@After scenario's hooks but it will be different for @AfterStep steps hooks because if everything is OK, we won't want to display all the step hook's statuses for every PASSED.

**Additional context**
N/A

**Comment by laxersaz** [comment]
Hello and thanks a lot for reporting. Do you have an example json file of a test result with after step hook failures?
Best, 
Benjamin

**Comment by tomaugs** [comment]
Hello, 

Here's the cucumber.json:

[
  {
    "line": 2,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 189889559,
              "status": "passed"
            },
            "match": {
              "location": "GlobalHooks.isReady()"
            }
          }
        ],
        "line": 5,
        "name": "Forex rates import date",
        "description": "",
        "id": "forex-rates;forex-rates-import-date",
        "after": [
          {
            "result": {
              "duration": 656686,
              "status": "passed"
            },
            "match": {
              "location": "GlobalHooks.embedScreenshots(Scenario)"
            }
          },
          {
            "result": {
              "duration": 18931,
              "status": "passed"
            },
            "match": {
              "location": "GlobalHooks.reportToALM(Scenario)"
            }
          },
          {
            "result": {
              "duration": 1298445883,
              "status": "passed"
            },
            "match": {
              "location": "GlobalHooks.cleanUp()"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 2476412151,
              "status": "passed"
            },
            "line": 6,
            "name": "I open the \"Loader Status\" screen",
            "match": {
              "arguments": [
                {
                  "val": "Loader Status",
                  "offset": 12
                }
              ],
              "location": "FxRatesSteps.openScreen(String)"
            },
            "after": [
              {
                "result": {
                  "error_message": "com.xxx.xxx.desktop.swing.asserts.AssertError: ERROR\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.lang.reflect.Method.invoke(Method.java:497)\r\n\tat cucumber.runtime.Utils$1.call(Utils.java:26)\r\n\tat cucumber.runtime.Timeout.timeout(Timeout.java:16)\r\n\tat cucumber.runtime.Utils.invoke(Utils.java:20)\r\n\tat cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)\r\n\tat cucumber.runtime.HookDefinitionMatch.runStep(HookDefinitionMatch.java:14)\r\n\tat cucumber.runner.TestStep.executeStep(TestStep.java:55)\r\n\tat cucumber.runner.TestStep.run(TestStep.java:42)\r\n\tat cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:56)\r\n\tat cucumber.runner.TestCase.run(TestCase.java:47)\r\n\tat cucumber.runner.Runner.runPickle(Runner.java:44)\r\n\tat cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)\r\n\tat cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:98)\r\n\tat cucumber.api.junit.Cucumber.runChild(Cucumber.java:55)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)\r\n\tat org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)\r\n\tat org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:352)\r\n\tat org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)\r\n\tat org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)\r\n\tat org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)\r\n\tat cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:107)\r\n\tat org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)\r\n\tat org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)\r\n\tat org.junit.runners.ParentRunner.run(ParentRunner.java:363)\r\n\tat org.junit.runners.Suite.runChild(Suite.java:128)\r\n\tat org.junit.runners.Suite.runChild(Suite.java:27)\r\n\tat org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)\r\n\tat org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)\r\n\tat java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)\r\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\r\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\r\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\r\n\tat java.lang.Thread.run(Thread.java:745)\r\n",
                  "duration": 392829,
                  "status": "failed"
                },
                "match": {
                  "location": "GlobalHooks.afterStepErrorHandling()"
                }
              }
            ],
            "keyword": "Given "
          }
        ],
        "tags": [
          {
            "name": "@all"
          },
          {
            "name": "@fxrates"
          },
          {
            "name": "@smoke"
          },
          {
            "name": "@fxrates-import"
          }
        ]
      }
    ],
    "name": "Forex rates",
    "description": "",
    "id": "forex-rates",
    "keyword": "Feature",
    "uri": "src/test/resources/features/fx-rates/FxRates.feature",
    "tags": [
      {
        "name": "@all",
        "type": "Tag",
        "location": {
          "line": 1,
          "column": 1
        }
      },
      {
        "name": "@fxrates",
        "type": "Tag",
        "location": {
          "line": 1,
          "column": 6
        }
      },
      {
        "name": "@smoke",
        "type": "Tag",
        "location": {
          "line": 1,
          "column": 15
        }
      }
    ]
  }
]

Br,

Thomas

**Comment by laxersaz** [comment]
For version 1.2.0 I added the capability to show failing before and after step hooks in the report details. However, Cucumber itself does not report a scenario as failed if the *last* after step hook fails. In this case this failure is not connected to the step before.
This seems to be an ongoing discussion since essentially after step hooks should not be used for assertions but rather for clean up.
So for now I will stick to the "official" way but continue research for sure.
If you have any documents or discussions you can provide to throw light on this matter, I would be glad if you can point me to some sources :-)
I will close this issue but create a research task as a follow up.

**Comment by laxersaz** [comment]
Follow up https://github.com/trivago/cluecumber-report-plugin/issues/68
