### ISSUE TITLE
Exception on rendering Karate step

### ISSUE THREAD

**Issue by laxersaz** [trivago/cluecumber-report-plugin#67]
```Step{line=10, name='match $.search == 0', keyword='And ', rows=[]}``` causes

Java method "com.trivago.rta.json.pojo.Step.returnNameWithArguments()" threw an exception when invoked on com.trivago.rta.json.pojo.Step object

**Comment by laxersaz** [comment]
This is fixed for release 1.2.0

**Comment by svarunbe** [comment]
@laxersaz 
Can you please let us know by when will you release the v1.2.0.
Im also facing this issue.

thanks

**Comment by laxersaz** [comment]
The ambitious plan is to release it tonight. I will announce it when it is ready.

**Comment by laxersaz** [comment]
Update: I will release tomorrow. The Cucumber 3 compatibility is almost done and I want to release that too.

**Comment by svarunbe** [comment]
@laxersaz 

It is working fine now.

Thank you.
