### ISSUE TITLE
Scenario with both 'Passed' and 'Skipped' steps shows 'Failed' scenario.

### ISSUE THREAD

**Issue by svarunbe** [trivago/cluecumber-report-plugin#70]
Hi @laxersaz 

Problem:
I observe that when a scenario has 'passed' and 'skipped' steps in it, then the scenario is marked as 'Failed' in the report.

Solution:
I think, a scenario should be 'Failed' only when it has 'Undefined' or 'Pending' or 'Failed' steps.
When a scenario has 'Passed' and 'Skipped' steps, the result should be 'Passed'.

Kindly let me know, if my understanding is wrong.

Thanks,

**Comment by laxersaz** [comment]
That is actually true. I will add this in for the next release.
Thanks for reporting!

Best,
Benjamin

**Comment by laxersaz** [comment]
Fix is included in this branch: https://github.com/trivago/cluecumber-report-plugin/tree/bugfix/wrong-status-on-skipped-and-passed-steps

**Comment by svarunbe** [comment]
@laxersaz 
Thanks for the fix.
Could you please make a sub release, so that I can use this?

One more question: 
Is it possible to show step arguments below each steps log in the report with expand and collapse feature.
Like how it is displaying stack trace for failed steps, it has to display for all the steps with option to show/hide. 

If yes, I will open a new ticket.

Thanks,

**Comment by laxersaz** [comment]
Yes I will make a sub release very soon for this fix that will also incorporate the correct step hook considerations.
For the feature, please open a new ticket 🙂

**Comment by laxersaz** [comment]
This will be released in 1.2.1 today.

**Comment by svarunbe** [comment]
@laxersaz 
Apologies. 
I realized after trying with the latest release that scenario with "passed" and "skipped" steps should have result as "skipped" since all the steps in that scenario is not "passed".

Please check the attached image. I have purposefully skipped 10 scenarios using karate.abort(), but then the result is shown as "passed".

![feature result](https://user-images.githubusercontent.com/22564247/43460019-01bcbf5c-94ed-11e8-8681-caf57c0f6066.JPG)

Thanks,

**Comment by laxersaz** [comment]
According to the Cucumber developers, in this case a scenario should be passed. Cluecumber considers it skipped if it only consists of skipped or pending steps.

**Comment by svarunbe** [comment]
@laxersaz 

Yes I agree that if a scenario should be skipped if all the steps in it are skipped.

But I observe a behaviour in "Cluecumber" that Background and Scenario steps are merge together to generate a report.

In that case, if any steps in background is passed, then the scenario result will always be passed irrespective of whether all steps in the scenario is 'Skipped'.

Kindly refer the attached two json file.
One feature file(ScenarioStatusSample.feature) with Background and other(ScenarioStatusSample2.feature) without Background. The later one seems to work fine.

[target.zip](https://github.com/trivago/cluecumber-report-plugin/files/2256283/target.zip)

I think Cluecumber should not combine "Background steps" and "Scenario Steps" as one.
Kindly clarify me.

Thanks

**Comment by laxersaz** [comment]
Hi @svarunbe ,
Background steps are basically syntactic sugar for steps that are repeated in each scenario. So technically it is correct that the scenario as a whole is marked as passed when Background steps pass and the rest are skipped. Your idea is definitely possible to implement but I guess this will be against the official Cucumber rules. I will ask in the Cucumber OSS group to get some more input on this.

**Comment by laxersaz** [comment]
I asked the Cucumber developers and they said the same. So the scenarios with passing background steps and skipped steps after it should be considered passed.

**Comment by svarunbe** [comment]
@laxersaz 
Yes. We have to follow the standards. But I do not see any practical use case where we will skip a scenario from start of "Background" step.
Could it be implemented with a flag as "strict". If the flag set as 'true', it can produce report as cucumber team suggested and if not, the report can produce as how user wants.

Please consider this use case.

Thanks,

**Comment by laxersaz** [comment]
I created a follow up, also to continue the discussion there:
https://github.com/trivago/cluecumber-report-plugin/issues/74
