### ISSUE TITLE
"doc_string" from json file should be displayed below every steps with option to show/hide it.

### ISSUE THREAD

**Issue by svarunbe** [trivago/cluecumber-report-plugin#73]
@laxersaz 
Currently, "doc_string" is displayed below the steps, only if it is failed, and it doesn't have option to hide it.

It would be better, if the report shows the "doc_string" below every steps irrespective of its status and an option to show/hide it.

Thanks,

**Comment by laxersaz** [comment]
Do you have an example json that shows this behavior?
Thanks :)

**Comment by laxersaz** [comment]
doc_strings can be present in all steps, not only in karate but also in other Cucumber frameworks. So I will add support for this. However, in the first iteration I will not make this toggle-able as this is a Cucumber feature that should be visible. In one of the next versions I will rethink how step data (embeddings, outputs, doc_strings) should be displayed

**Comment by laxersaz** [comment]
Ready for release in 1.3.0

**Comment by svarunbe** [comment]
Hi @laxersaz,

It is great to have this feature. Thank for that.
Can we expect the expand collapse feature any time sooner as the doc_string for each step added cause the report not readable much.

Thanks

**Comment by laxersaz** [comment]
Hello @svarunbe ,
I created a follow up task for this and plan to do it for the next release: #84

**Comment by svarunbe** [comment]
@laxersaz 

Great. Appreciate that.
