### ISSUE TITLE
Improve the display of data tables parameters and stacktraces

### ISSUE THREAD

**Issue by tomaugs** [trivago/cluecumber-report-plugin#75]
### Expected behavior
Better formatting the display of data tables parameters and stacktraces.

### Actual behavior

- Data Tables parameters:
For now the data tables headers and values are split for each space with a new line. And if you have a big list of parameters it could be very hard to read all the table.

- Stacktraces:
Stacktraces can be hard to read also, especially if you have a lot of assertions. In some cases I could have a SoftAssertions with asserts within a loop and then an assertAll.
It would be nice to have a formatted stacktrace like we have in the cucumber html reports or in the output console.

Tips for data tables and stacks: 
- Separate the content of data tables parameters from the div which displays  the step name. We would have space to take more width.
- Maybe take the whole width of the display (step number + step names + step durations + step statuses columns), ex: col-12 for the div which contains the parameters and the stack trace.

### Reproduction steps
Example of data table parameters:

Then the batch jobs should succeed within the given time in minutes:
      | Job Number	| Job Name                              | Expected Duration	|
      | XXXXX		| One word, two words, three words	| 10			|									
      | XXXXX		| One word, two words, three words	| 60 			|
      | XXXXX		| One word, two words, three words	| 4 			|
      | XXXXX		| One word, two words, three words	| 5 			|
      | XXXXX		| One word, two words, three words	| 12 			|
      | XXXXX		| One word, two words, three words	| 12 			|
      | XXXXX		| One word, two words, three words	| 2 			|
      | XXXXX		| One word, two words, three words	| 6 			|
      | XXXXX		| One word, two words, three words	| 3 			|
      | XXXXX		| One word, two words, three words	| 25 			|
      | XXXXX		| One word, two words, three words	| 15 			|
      | XXXXX		| One word, two words, three words	| 90 			|
      | XXXXX		| One word, two words, three words	| 90 			|
      | XXXXX		| One word, two words, three words	| 2 			|
      | XXXXX		| One word, two words, three words	| 6 			|
      | XXXXX		| One word, two words, three words	| 60 			|
      | XXXXX		| One word, two words, three words	| 15 			|
      | XXXXX		| One word, two words, three words	| 20 			|
      | XXXXX		| One word, two words, three words	| 1 			|
      | XXXXX		| One word, two words, three words	| 2 			|
      | XXXXX		| One word, two words, three words	| 5 			|
      | XXXXX		| One word, two words, three words	| 8 			|
      | XXXXX		| One word, two words, three words	| 7 			|
      | XXXXX		| One word, two words, three words	| 5 			|
      | XXXXX		| One word, two words, three words	| 5 			|
      | XXXXX		| One word, two words, three words	| 6 			|
      | XXXXX		| One word, two words, three words	| 20 			|
      | XXXXX		| One word, two words, three words	| 45 			|
      | XXXXX		| One word, two words, three words	| 6 			|

Exemple of stack trace:
`
org.assertj.core.api.SoftAssertionError: The following 13 assertions failed: 1) [Check that the duration of the job's execution '12150:Fixed Income Data Export' is less than the expected time] Expecting: <7> to be less than or equal to: <0> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 2) [Check that the duration of the job's execution '12910:Holdings daily Profit and Loss' is less than the expected time] Expecting: <39> to be less than or equal to: <15> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 3) [Check that the duration of the job's execution '12930:Performance Attribution' is less than the expected time] Expecting: <7> to be less than or equal to: <2> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 4) [Check that the duration of the job's execution '12940:Benchmark daily Profit and Loss' is less than the expected time] Expecting: <52> to be less than or equal to: <0> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 5) [Check that the duration of the job's execution '14020:Offline unbundling pre-computing' is less than the expected time] Expecting: <21> to be less than or equal to: <15> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 6) [Check the status of the job's execution '15150:Fund Information Replication Service'] Expecting: <"COMPLETED WITH ERRORS"> not to contain: <"ERRORS"> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:196) 7) [Check that the duration of the job's execution '15150:Fund Information Replication Service' is less than the expected time] Expecting: <45> to be less than or equal to: <20> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 8) [Check that the duration of the job's execution '16000:CRD Portfolio Reference Data' is less than the expected time] Expecting: <2> to be less than or equal to: <1> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 9) [Check that the duration of the job's execution '18500:Offline Investment Reporting' is less than the expected time] Expecting: <4> to be less than or equal to: <0> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 10) [Check the status of the job's execution '19000:Forex Accomodation Trading - Morning Run'] Expecting: <"COMPLETED WITH ERRORS"> not to contain: <"ERRORS"> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:196) 11) [Check that the duration of the job's execution '19000:Forex Accomodation Trading - Morning Run' is less than the expected time] Expecting: <5> to be less than or equal to: <0> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 12) [Check that the duration of the job's execution '19500:Strategy Housekeeping - part 2 (per portfolio)' is less than the expected time] Expecting: <35> to be less than or equal to: <0> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) 13) [Check that the duration of the job's execution '19600:Economic Exposure computing' is less than the expected time] Expecting: <35> to be less than or equal to: <0> at AdministrationPageObject.lambda$4(AdministrationPageObject.java:199) at org.assertj.core.api.SoftAssertions.assertAll(SoftAssertions.java:133) at com.pictet.pamfolio.desktop.swing.pageobjects.AdministrationPageObject.checkBatchStatusAndDuration(AdministrationPageObject.java:213) at com.pictet.pamfolio.desktop.swing.steps.AdministrationSteps.controlBatchJobs_aroundBody50(AdministrationSteps.java:272) at com.pictet.pamfolio.desktop.swing.steps.AdministrationSteps.controlBatchJobs_aroundBody51$advice(AdministrationSteps.java:56) at com.pictet.pamfolio.desktop.swing.steps.AdministrationSteps.controlBatchJobs(AdministrationSteps.java:1) at ✽.the batch jobs should succeed within the given time in minutes:(src/test/resources/features/technical/AdministrationConsole.feature:32)
`

**Comment by laxersaz** [comment]
Hello @tomaugs ,
I was on holidays so I could not look into this request yet. But rest assured, I will :-)
Best,
Benjamin

**Comment by laxersaz** [comment]
Ready for release in 1.3.0

**Comment by tomaugs** [comment]
Hello @laxersaz ,

I was also on holidays and I just come back. 
Thanks a lot for this new release which increases a lot the readyness of reports.

Br,

Thomas

**Comment by laxersaz** [comment]
Thanks a lot for your kind words, @tomaugs !
