### ISSUE TITLE
Unable to get the screenshot attached to reports in case of failures

### ISSUE THREAD

**Issue by subodh2691** [trivago/cluecumber-report-plugin#76]
Hello,

I was trying to use the plugin but I am unable to get the screenshots attached to the report in case of any failures. Can you help me here?

**Comment by subodh2691** [comment]
POM.xml ->

<plugin>
        <groupId>com.trivago.rta</groupId>
        <artifactId>cluecumber-report-plugin</artifactId>
        <version>1.2.1</version>
        <executions>
            <execution>
                <id>report</id>
                <phase>post-integration-test</phase>
                <goals>
                    <goal>reporting</goal>
                </goals>
            </execution>
        </executions>
        <configuration>
            <sourceJsonReportDirectory>${project.build.directory}/cucumber-report/</sourceJsonReportDirectory>
            <generatedHtmlReportDirectory>${project.build.directory}/test-report</generatedHtmlReportDirectory>
        </configuration>    
    </plugin>

**Comment by laxersaz** [comment]
Hello @subodh2691 ,
if you attach the screenshots to the scenario in your test framework, they are automatically displayed in the report. Can you check if the screenshot is inside one of your generated Cucumber JSON files? 

This should look like this:

```
"embeddings": [
              {
                "mime_type": "image/png",
                "data": "some large base64 encoded string"
             }
```

**Comment by subodh2691** [comment]
Hi @laxersaz, I was expecting this output in my json files, which is missing. 
I am using this:
`scenario.embed(((TakesScreenshot)driver).getScreenshotAs(OutputType.BYTES),` `"image/png");`
But using above code throws NullPointerException in Java. Is there something else which needs to be included?

**Comment by laxersaz** [comment]
Sorry but unfortunatelly I cannot debug your test code for you. If there are problems with Cluecumber itself I am more than happy to help. In your case though, it behaves as expected.
