### ISSUE TITLE
Cluecumber trying to parse other JSON files located in class path

### ISSUE THREAD

**Issue by alenmeister** [trivago/cluecumber-report-plugin#77]
**Describe the bug**
It looks as Cluecumber is trying to parse other JSON files located in class path when generating the report. I currently have a bunch of test data stored as JSON objects under test/resources/data/foo.json and there's always an error thrown after my build is done.

**Additional context**
`[ERROR] Could not parse JSON in file 'C:\Users\H804288\Projects\engine-selenium-regress\target\test-classes\data\01025700410.json': java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2
 path $`

**Comment by laxersaz** [comment]
Hello @alenmeister ,
thanks for the report. I will look into this behavior.

**Comment by alenmeister** [comment]
Oh, shoot, I didn't specify where my config.properties file was. I had it under src/test/resources/config/config.properties and once I moved it out from the config folder the error appears to be gone...

**Comment by laxersaz** [comment]
Hi again, thanks for letting me know!
Can this issue be closed then?
