### ISSUE TITLE
Is it possible for me to use gradle rather than maven?

### ISSUE THREAD

**Issue by robsonpolicarpo** [trivago/cluecumber-report-plugin#84]
Is it possible for me to use gradle rather than maven?

**Comment by laxersaz** [comment]
Hello @robsonpolicarpo , as I have too little gradle experience, I cannot really help you here (yet). In the future, I might consider porting Cluecumber over but at this moment, it is Maven only.
However, as far as I know you can also invoke maven goals through gradle (https://github.com/dkorotych/gradle-maven-exec-plugin) - maybe this would be an option?

**Comment by JavaanseHZ** [comment]
Hey @laxersaz @robsonpolicarpo ,

I've written a gradle wrapper for cluecumber, since I liked the UI a lot better than other cucumber reporting plugins and we're using gradle.

Github: https://github.com/JavaanseHZ/cluecumber-report-gradle-plugin
Gradle Plugin portal: https://plugins.gradle.org/plugin/de.javaansehz.cluecumber-report-gradle-plugin

I just wanted to inform you guys to make sure it's ok with you :)
Cheers

**Comment by laxersaz** [comment]
Hi @JavaanseHZ ,

this is really cool! I will try this out for sure.

Thanks a lot,
Benjamin (laxersaz)

**Comment by kalhanrl** [comment]
Hi @JavaanseHZ  , 
I am getting this error when executing the gradle task. 
* What went wrong:
Execution failed for task ':generateCluecumberReports'.
> com.trivago.cluecumber.exceptions.CluecumberPluginException: Unable to traverse JSON files in target/new-report

Could you please guide me on this

**Comment by laxersaz** [comment]
Did you check that
- tests were run
- json was generated in `target/new-report`
?

Because it sounds like it didn't.

**Comment by kalhanrl** [comment]
Hi,
No, tests not getting executed, before that it fails when used the "gradlew generateCluecumberReports" command. target-new folders created but no json is there
When executed using "gradlew cucumber" command, tests executed but not generating the target-new folder even. Tests are passing though

**Comment by laxersaz** [comment]
Is your runner including the cucumber json plugin?

**Comment by kalhanrl** [comment]
I added json plugin, now the json is created. 

args = ['--plugin', 'pretty', '--plugin','json:target/cucumber-reports/Cucumber.json', '--glue', 'stepdefs', 'src/test/resources','--tags', '~@wip']

Config for the plugin is as follows:

cluecumberReports {
    sourceJsonReportDirectory = 'target/cucumber-reports/'
    generatedHtmlReportDirectory = 'target/new-report'
}        

But when I execute the "gradlew generateCluecumberReports" command, still gives the same error.

> com.trivago.cluecumber.exceptions.CluecumberPluginException: Unable to traverse JSON files in target/cucumber-reports/

**Comment by kalhanrl** [comment]
When I execute the gradlew cucumber command, json is created and attachments folder is empty. No html report is created. Tests passed

**Comment by laxersaz** [comment]
One is executing the tests, the other is executing the report generation. So you probably have to use both or a lifecycle (not sure if this exists like this in Gradle) that includes both.

**Comment by JavaanseHZ** [comment]
As @laxersaz said, the both tasks are not linked by default, so they can be invoked separately.
If you want to chain them in one command, you can execute the following:

`gradlew cucumber generateCluecumberReports`

If you want to link them permanently you can put this in your build.gradle:

`cucumber.finalizedBy generateCluecumberReports`

This means that every time the cucumber task is invoked, it will also invoke the generateCucumberTask afterwards, so simply putting the following would suffice after this:

`gradlew cucumber`

If you're still having problems with the file paths, I'd try using absolute paths (e.g. c:\tmp on Windows or /tmp on Linux) for troubleshooting and go from there. It's sometimes a bit tricky with relative paths:

```
args = ['--plugin', 'pretty', '--plugin','json:/tmp/reports/cucumber.json', '--glue', 'stepdefs', 'src/test/resources','--tags', '~@wip']
```

```
cluecumberReports {
   sourceJsonReportDirectory = /tmp/reports'
   generatedHtmlReportDirectory = '/tmp/new-report'
}
```

Maybe putting an example cucumber.json report in the sourceJsonReportDirectory manually and going from there might also help.

**Comment by kalhanrl** [comment]
Hi! @JavaanseHZ  Thanks you :) 

I tried your solutions. Json file is created inside the temp folder, **but not the html report**. 

I used this command: gradlew cucumber generateCluecumberReports 
Tests are passed. 

Following are my build.gradle settings
plugins {
    id "de.javaansehz.cluecumber-report-gradle-plugin" version "1.1.4"
}

cluecumberReports {
    sourceJsonReportDirectory = '/tmp/reports'
    generatedHtmlReportDirectory = '/tmp/new-report'
}

 args = ['--plugin', 'pretty', '--plugin', 'html:target/report','--plugin','json:/tmp/reports/cucumber.json', '--glue', 'stepdefs', 'src/test/resources','--tags', '~@wip']

**Comment by JavaanseHZ** [comment]
Just to make sure: you're looking for the html reports in this folder:
generatedHtmlReportDirectory = '/tmp/**new-report**'
Sorry for asking if that's obvious, sometimes stuff like like this is easy to miss.

Anyway, I uploaded a minimal example here:
https://github.com/JavaanseHZ/cluecumber-report-gradle-plugin-example
Try it out with `./gradlew cucumber` and see if you get html reports in the build/html-report folder.

**Comment by kalhanrl** [comment]
Thanks a lot ! It worked. I referred your build.gradle and changed my one with missing configs. Now it works fine :)

**Comment by pooja4099** [comment]
@JavaanseHZ - the reports are not getting generated if there is a failed test case, how do i configure it to ignore any failures and continue to generate report?

**Comment by JavaanseHZ** [comment]
> @JavaanseHZ - the reports are not getting generated if there is a failed test case, how do i configure it to ignore any failures and continue to generate report?
I'm not sure I understand you correctly. The reports are based on test results getting written by cucumber. Do you mean a) you don't get the test result json file as output from cucumber or b) that the output files are there but the reports are not generated. a) is more of a cucumber problem unrelated to reports. b) would be rather strange, but I can check tomorrow evening. Just in case: do you execute the Gradle tasks separately? If you configure them to be dependent on each other, it might prevent the latter from being executed.

**Comment by pooja4099** [comment]
hi @JavaanseHZ , thank you for coming back on this. the json file was there html report was not being generated. 
I added the below option and it was sorted.
cucumberTest.ignoreFailures = true
________here is the snippet of my gradle file__________

task cucumberTest(type: Test) {
    dependsOn assemble, compileTestJava
    doLast {
        javaexec {
            main = "cucumber.api.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = ['--tags', '@Test', '--plugin', 'pretty',
                    '--plugin', "json:${buildDir}/reports/cucumber.json", '--plugin', 'html:reports/',
                    '--glue', 'steps', "${projectDir}/src/test/resources/features"]
        }
    }
}

cucumberTest.finalizedBy(generateCluecumberReports)

cluecumberReports {
    sourceJsonReportDirectory = "${buildDir}/reports"
    generatedHtmlReportDirectory = "${buildDir}/html-reports"
}
cucumberTest.ignoreFailures = true
