### ISSUE TITLE
Report layout for scenarios breaks when using broad tables with many attributes

### ISSUE THREAD

**Issue by valdeziscoming** [trivago/cluecumber-report-plugin#85]
When using tables with many attributes, the layout is broken

**Expected behavior**
panel should rendered more flexible, or in two parts (line break)

![image](https://user-images.githubusercontent.com/16211650/45143539-dd06a100-b1bb-11e8-88b0-97ad05e22ba7.png)

**Comment by laxersaz** [comment]
Hi @valdeziscoming !
Thanks for reporting this, I honestly didn't expect such large tables to exist in test cases.

**Comment by laxersaz** [comment]
This panel will be responsive / scrollable in 1.4.0

**Comment by valdeziscoming** [comment]
Thanks !
