### ISSUE TITLE
Incorrect label for Tag Summary Result Chart under All Tags

### ISSUE THREAD

**Issue by hanikhan** [trivago/cluecumber-report-plugin#90]
**Describe the bug**
Incorrect label for Tag Summary Result Chart under All Tags

**To Reproduce**
1. Add a few tags in your feature file
2. Observe legends for 'Tag Summary Result Chart' under all tags report
3. Legends read 'passed' , 'failed' and 'passed'

**Expected behavior**
 Legends should read 'passed' , 'failed' and 'skipped'

**Comment by laxersaz** [comment]
This will be included in the next release.
