### ISSUE TITLE
The Plugin does not show the correct content for text and html format attachments.

### ISSUE THREAD

**Issue by Rameshwar244** [trivago/cluecumber-report-plugin#97]
Hi Team,

The Plugin does not show the correct content for text and html format attachments in AfterHooks section.
The attachments are added using below code.

HTML Attachment:-

		StringBuilder stringBuilder = new StringBuilder("<table border='1' cellpadding='10' cellspacing='0'><tbody><tr><th><B>Field Name</th><th><B>Field Value</th></tr><tr><td><B>Field Name One</td><td><B>Field Value One</td></tr><tr><td><B>Field Name Two</td><td><B>Field Value Two</td></tr>");
		stringBuilder.append("</tbody></table>");
		scenario.embed(stringBuilder.toString().getBytes(),"text/html");
Text Attachment:-

		scenario.embed(FileUtils.readFileToByteArray(new File("target/Log/Scenario_Execution_"+scenario.getId()+".log")), "text/plain");

**To Reproduce**
1. Try to generate the report for attached "cucumber.json" file. 
2. Check Scenario Details in generated reports (see attachments section)

**Expected behavior**
Actual content of the attachments should be displayed as per given formats.

**Actual behavior**
1) Embedding content is displayed as it is. 
2) screenshots are displayed properly.

**Attachments**
PFA Sample json and Reports
[JSON and Reports.zip](https://github.com/trivago/cluecumber-report-plugin/files/2499424/JSON.and.Reports.zip)

**Additional context**

**Comment by Rameshwar244** [comment]
Hi Benjamin,

First of all, Thanks for such a great reporting plugin for cucumber reporting. I have recently started using this. I really appreciate the work done.
I would also like to contribute for improving the same. This will be my first contribution to open source community.
I have already started working on this issue.
I will be creating pull request for the same once I finish the fix.

Kindly help me with the guidelines and practices on Github if anything goes wrong from my side.

Thanks,
Rameshwar Shiral

**Comment by tobiswajitdas** [comment]
Greetings, Jenkins HTML report is not displaying the charts and animations from Jenkins. However, opening the same HTML file locally works perfectly. I have seen some old posts but if anyone can direct me to the solution would be great. thank you.

**Comment by laxersaz** [comment]
Hi! I'm looking forward to your pull request.

**Comment by laxersaz** [comment]
Hello,

 

Please open a separate issue as your comment was unrelated to the thread.

 

Thanks!

**Comment by Rameshwar244** [comment]
Hi Benjamin,

The bug is fixed with Pull request https://github.com/trivago/cluecumber-report-plugin/pull/99.
Please review the same.

**Comment by Rameshwar244** [comment]
Hi,

I am working on it. will commit required changes today.

Thanks,
Rameshwar
