### ISSUE TITLE
Greetings, Jenkins HTML report is not displaying the charts and animations from Jenkins. However, opening the same HTML file locally works perfectly. I have seen some old posts but if anyone can direct me to the solution would be great. thank you.

### ISSUE THREAD

**Issue by laxersaz** [trivago/cluecumber-report-plugin#98]
_Originally posted by @tobiswajitdas in https://github.com/trivago/cluecumber-report-plugin/issues/97#issuecomment-431734596_

**Comment by laxersaz** [comment]
Hello @tobiswajitdas
Please see https://stackoverflow.com/questions/35783964/jenkins-html-publisher-plugin-no-css-is-displayed-when-report-is-viewed-in-j about the jenkins content policy settings.

**Comment by boris779** [comment]
Thx @laxersaz stackoverflow solution worked for me!
